### ISSUE TITLE
Long collection times over large distributed network

### ISSUE THREAD

**Issue by Shadbehemoth** [akpw/mktxp#10]
The collector takes a very long time when trying to collect data on a lot of routers over IPSec.

Is the collection done with one router after another or are they done simultaneously?

Is there a way to timeout a collection if it takes longer than say 10s? Certain sites have poor connection at certain times, so it would bring the entire collector down when they cannot respond in time.

Thank you for your attention.

**Comment by akpw** [comment]
mktxp allows customization of std socket timeout (```mktxp edit -i```), though at that point does not support limiting overall collection time.  it indeed can be added in a future release, same thing for parallel processing for multiple routers.

**Comment by akpw** [comment]
@Shadbehemoth fyi, both parallel router fetch & configurable individual / overall scrape timeouts are now implemented
Feel free to check it out, configuring the default values
```
fetch_routers_in_parallel = False   # Set to True if you want to fetch multiple routers parallel
max_worker_threads = 5              # Max number of worker threads that can fetch routers. Meaningless if fetch_routers_in_parallel is set to False
    
max_scrape_duration = 10            # Max duration of individual routers' metrics collection 
total_max_scrape_duration = 30      # Max overall duration of all metrics collection 

```

 for your setup as needed, via: 
```
mktxp edit -ed nano -i
```

**Comment by Shadbehemoth** [comment]
Awesome thank you. Recently started using this again and grateful of the feature.
