### ISSUE TITLE
DHCP records remain empty with "remote_dhcp_entry" set to "True"

### ISSUE THREAD

**Issue by FinlayDaG33k** [akpw/mktxp#108]
I've migrated my CAPsMAN from my old main router (CCR2004) to a new RB5009 earlier today, however this seems to break DHCP resolution.  
According to [the docs](https://github.com/akpw/mktxp?tab=readme-ov-file#remote-dhcp-resolution) I had to add the `remote_dhcp_entry` parameter to my config, however, it seems to still not resolve, instead showing the MAC addresses of the clients.  
My question is whether I did something wrong or whether this is a bug of sorts.

![afbeelding](https://github.com/akpw/mktxp/assets/13424273/b0069bb3-686c-4612-b10c-7ee9c423ce96)

```
[RB5009UG+S+]
  no_ssl_certificate = False
  ssl_certificate_verify = False
  installed_packages = False
  interface = True
  public_ip = False
  capsman = True
  poe = False
  wireless_clients = True
  monitor = True
  enabled = True
  connections = False
  ipv6_neighbor = False
  dhcp_lease = True
  capsman_clients = True
  firewall = False
  use_ssl = False
  netwatch = False
  ipv6_firewall = False
  dhcp = True
  route = False
  pool = False
  use_comments_over_names = True
  wireless = True
  hostname = 192.168.0.7
  username = mktxp
  password = LAMEPASSWORD
  port = 8728
  remote_dhcp_entry = True
```

**Comment by akpw** [comment]
> According to [the docs](https://github.com/akpw/mktxp?tab=readme-ov-file#remote-dhcp-resolution) I had to add the remote_dhcp_entry parameter to my config

right, the docs also say "MKTXP entry in this context can be any other mktxp.conf entry". 
`True` is not the right value in this context
