### ISSUE TITLE
Metrics for kid-control devices not working

### ISSUE THREAD

**Issue by 3guboff** [akpw/mktxp#111]
Technical details in [PR comment ](https://github.com/akpw/mktxp/pull/96)

It was tested with the latest docker image and from the source - same result.

Please, can someone fix this?
![_b1fcb5f7-3162-4f88-bbb0-cda3e95d886e](https://github.com/akpw/mktxp/assets/1561986/e9a24375-a8af-4468-8cdd-da47c830649f)

**Comment by akpw** [comment]
@3guboff I do not use kid control, but tested this for you again with this simple setup:

```
> ip/kid-control/print detail  
 0 L name="BD" sun=0s-23h59m mon=0s-23h59m tue=0s-23h59m wed=0s-23h59m thu=0s-23h59m fri=0s-23h59m sat=0s-23h59m rate-limit="2M" tur-sun="" tur-mon="" tur-tue="" tur-wed="" tur-thu="" tur-fri="" tur-sat="" 
> ip/kid-control/device/print detail  
 0 L  name="Samsung Galaxy Tab S8" mac-address=06:XX:XX:XX:XX:00 user=BD ip-address=10.XX.XX.XX activity="" rate-down=0bps rate-up=0bps bytes-down=59.6GiB bytes-up=5.2GiB idle-time=2s 
```

and here is my output: 
```
> wget -O - http://localhost:49090/ | grep -i kid
...

mktxp_firewall_filter_total{log="0",name="| forward | jump | jump to kid-control rules",routerboard_address="10.XX.XX.1",routerboard_name="MKT-GT"} 1.589781978486e+012
mktxp_firewall_filter_total{log="0",name="| kid-control | accept | Samsung Galaxy Tab S8, kid-control",routerboard_address="10.XX.XX.1",routerboard_name="MKT-GT"} 6.6060558e+07
...

# HELP mktxp_kid_control_device_info Kid-control device Info
# TYPE mktxp_kid_control_device_info gauge
mktxp_kid_control_device_info{disabled="0",ip_address="10.xx.xx.xx",mac_address="06:XX:XX:XX:C3:00",name="Samsung Galaxy Tab S8",routerboard_address="10.XX.XX.1",routerboard_name="MKT-GT",user="BD"} 1.0

# HELP mktxp_kid_control_device_bytes_down Number of received bytes
# TYPE mktxp_kid_control_device_bytes_down gauge
mktxp_kid_control_device_bytes_down{mac_address="06:XX:XX:XX:C3:00",name="Samsung Galaxy Tab S8",routerboard_address="10.XX.XX.1",routerboard_name="MKT-GT",user="BD"} 6.3951389458e+010

# HELP mktxp_kid_control_device_bytes_up Number of transmitted bytes
# TYPE mktxp_kid_control_device_bytes_up gauge
mktxp_kid_control_device_bytes_up{mac_address="06:XX:XX:XX:C3:00",name="Samsung Galaxy Tab S8",routerboard_address="10.XX.XX.1",routerboard_name="MKT-GT",user="BD"} 5.580357782e+09

# HELP mktxp_kid_control_device_rate_down Device rate down
# TYPE mktxp_kid_control_device_rate_down gauge
mktxp_kid_control_device_rate_down{mac_address="06:XX:XX:XX:C3:00",name="Samsung Galaxy Tab S8",routerboard_address="10.XX.XX.1",routerboard_name="MKT-GT",user="BD"} 0.0

# HELP mktxp_kid_control_device_rate_up Device rate up
# TYPE mktxp_kid_control_device_rate_up gauge
mktxp_kid_control_device_rate_up{mac_address="06:XX:XX:XX:C3:00",name="Samsung Galaxy Tab S8",routerboard_address="10.XX.XX.1",routerboard_name="MKT-GT",user="BD"} 0.0

# HELP mktxp_kid_control_device_idle_time Device idle time
# TYPE mktxp_kid_control_device_idle_time gauge
mktxp_kid_control_device_idle_time{mac_address="06:XX:XX:XX:C3:00",name="Samsung Galaxy Tab S8",routerboard_address="10.XX.XX.1",routerboard_name="MKT-GT",user="BD"} 7.0

mktxp_collection_time_total{name="KidControlCollector",routerboard_address="10.XX.XX.1",routerboard_name="MKT-GT"} 384.31762577965856
```

Contrary to what you say the metrics seems to be present, so just checking -- are you sure everything related on your end has been setup correctly?

**Comment by 3guboff** [comment]
You're right, I was wrong about testing. What I missed during testing: it's setting up the specific user(s) on the "Devices" level - if the setup is specific user - all work correctly. Because using dynamic devices is impossible in the current state [I've created PR](https://github.com/akpw/mktxp/pull/112) with a fix with a small improvement.

**Comment by akpw** [comment]
>using Dynamic devices is impossible

can you pls expand a bit on your use case here?

**Comment by 3guboff** [comment]
> > using Dynamic devices is impossible
> 
> can you pls expand a bit on your use case here?

Sorry for the delay, here is the logic:
Ideas of using **kid-control** are not controlling a specific kid and his device(s) but monitoring in real-time all devices that are connected to the router (wired/wireless).
You creating a "kid" called Monitor that is used for monitoring 24/7
![image](https://github.com/akpw/mktxp/assets/1561986/604ae0db-b82d-4cb8-949e-d83dc1b1d3a3)
All devices will be dynamic != added manually
![image](https://github.com/akpw/mktxp/assets/1561986/00a9dde3-547e-41a9-aeea-a29ff6c146d4)

**Comment by akpw** [comment]
OK this use-case makes sense, though probably requires an additional config option

**Comment by akpw** [comment]
@3guboff fyi I added the [mktxp.conf option](https://github.com/akpw/mktxp#getting-started), feel free to check it out with `kid_control_dynamic = True`

**Comment by akpw** [comment]
added to the [dashboard](https://grafana.com/grafana/dashboards/13679-mikrotik-mktxp-exporter/) as well:
<img width="200" alt="Screenshot 2024-04-10 at 15 50 28" src="https://github.com/akpw/mktxp/assets/5028474/21a5484b-4637-4cd8-a30e-285ae6bcf3e7">
