### ISSUE TITLE
Feature request - Shared default config

### ISSUE THREAD

**Issue by thefeli73** [akpw/mktxp#119]
I would like to request an improvement to the config file for easier management of configs with many routerboards: a shared default config. Anything in `[default]` will be applied to all routerboards, but overridden by routerboard-specific configs.
Example `mktxp.conf`:

```
[default]
username = mktxp
password = xxxxxx
use_ssl = False     
no_ssl_certificate = False
ssl_certificate_verify = False 
installed_packages = True
dhcp = True
dhcp_lease = True

[router1]
hostname=10.x.x.1

[router1]
hostname=10.x.x.2

[router3]
hostname=10.x.x.3
dhcp = False
dhcp_lease = False

```

**Comment by akpw** [comment]
@thefeli73 OK done, feel free to check it out & comment

**Comment by akpw** [comment]
described [here](https://github.com/akpw/mktxp#getting-started), including a hint on automatically migrating from the old format
