### ISSUE TITLE
"expires_after" label of mktxp_dhcp_lease_info has unnecessarily high cardinality

### ISSUE THREAD

**Issue by ashtuchkin** [akpw/mktxp#12]
First of all, thanks for working on this project, it's very useful!

The issue I'd like to report is that `expires_after` label of `mktxp_dhcp_lease_info` metric has values like "30m18s", "59m18s", etc. For each different value prometheus stores a separate series, unnecessarily adding load to the storage database. It's already the largest-cardinality label in my prometheus database, after running mktxp for ~3 hours (you can look at the metrics at http://<prometheus host:port>/tsdb-status ).

What do you think about changing the way the lease expiration time is reported? E.g. it could be a separate metric like `mktxp_dhcp_lease_expires` with value = unix timestamp of expiration? That would put much less load on the database and would probably be more useful for showing in grafana as well.

**Comment by akpw** [comment]
@ashtuchkin correct, changing the metric to smth like:

```
mktxp_dhcp_lease_info_expires{active_address="xx.xx.xx.xx",address="xx.xx.xx.xx",comment="...", host_name="...",mac_address="...",routerboard_address="xx.xx.xx.xx",routerboard_name="...",server="..."} 1327312578
```

makes a lot of sense.  I do plan to make optimizations like that across mktxp, so pls keep tuned.

**Comment by ashtuchkin** [comment]
Awesome, looking forward to it!

**Comment by forresthopkinsa** [comment]
Has this problem been resolved?

**Comment by akpw** [comment]
@ashtuchkin, @forresthopkinsa: this should be fixed in the latest, grafana dashboard was updated as well
