### ISSUE TITLE
Erro 111 - Connection Refused

### ISSUE THREAD

**Issue by julistrapa** [akpw/mktxp#121]
Hi guys i new on scraping metrics, and i tried to install the Mktxp tool and a error message come when i tried to mktxp print, if anyone can help with that, i think it was on my router, but i tried everything, disabling Firewall, creat rules for the port and nothing solved, the print is below

PS - I already make the connection with prometheus, the real problem is the communication MKTXP - RouterOS
![Screenshot_2](https://github.com/akpw/mktxp/assets/160742786/a1758313-5c51-4171-b5c0-6ec94e7182e6)

**Comment by akpw** [comment]
check this on your router:
```
ip/service/print  
user/print detail 
```

and then see if this is in sync with your ```mktxp.conf``` settings:
```mktxp edit -ed nano```

more details [here](https://github.com/akpw/mktxp#getting-started)
