### ISSUE TITLE
Support for arm devices, installed on routeros devices

### ISSUE THREAD

**Issue by llity** [akpw/mktxp#122]
Hello,

Hopefully devices such as arm64 will be supported for easy installation inside routeros.

Thanks.

**Comment by akpw** [comment]
@llity arm64 should be a supported platform? here is the list from the [current docker build](https://github.com/akpw/mktxp/blob/main/.github/workflows/build-and-push.yaml)

```
      ### platforms to build for
      ### defaults to linux/amd64
      ### other options: linux/amd64,linux/arm64,linux/arm/v7
      platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/386
```

**Comment by llity** [comment]
@akpw I will install it directly on the wired router (routeros), thanks!

**Comment by akpw** [comment]
yes there seems to be a bunch of earlier builds there submitted by various people, though you'd be probably better off just using the [latest](https://github.com/akpw/mktxp/pkgs/container/mktxp/192413670?tag=latest)
