### ISSUE TITLE
[request] Disabling the internal speedtest, mktxp_internet_bandwidth

### ISSUE THREAD

**Issue by ThatCoffeeGuy** [akpw/mktxp#124]
Hello,

Thank you so much for your work on this, this is is an amazing tool. The only feature request I'd have, is that I'd like to disable the internal periodic speedtest, shown as mktxp_internet_bandwidth in grafana. 

For now this is my solution:

```
docker exec -it mktxp /bin/sh
cd /usr/local/bin
/usr/local/bin # mv speedtest speedtest.bak
/usr/local/bin # mv speedtest-cli speedtest-cli.bak
```

**Comment by akpw** [comment]
@ThatCoffeeGuy thanks for the good words
regarding the bandwidth test, you can it as described [here](https://github.com/akpw/mktxp#mktxp-system-configuration), essentially 
```
mktxp edit -i
...
bandwidth = False 
```
It should be the default already, but if not should be simple to set it up as needed

**Comment by ThatCoffeeGuy** [comment]
> @ThatCoffeeGuy thanks for the good words regarding the bandwidth test, you can disable it as described [here](https://github.com/akpw/mktxp#mktxp-system-configuration), essentially
> 
> ```
> mktxp edit -i
> ...
> bandwidth = False 
> ```
> 
> It should be the default already, but if not should be simple to set it up as needed

Oh damn I'm sorry, I completely missed this, even though I was looking for it... thank you!
