### ISSUE TITLE
default speedtest cost me hundreds... Bandwidth is expensive in Australia

### ISSUE THREAD

**Issue by shleeable** [akpw/mktxp#126]
Hello.. last month I added your service to my stack and suddenly noticed my bandwidth was eating 100GB~ a day.. 

Considering I only have 3TB a month... I had to pay for more bandwidth 

please consider lowering this default test to 4 times a day instead of every 5 minutes or whatever.

**Comment by akpw** [comment]
@shleeable you can change the bandwidth test frequency or disable it it altogether as described [here](https://github.com/akpw/mktxp#mktxp-system-configuration), e.g. 
```
mktxp edit -i
...
bandwidth = False 
```

**Comment by shleeable** [comment]
@akpw this is a danger default.

**Comment by akpw** [comment]
@shleeable the bandwidth test should have been disabled by default about an year ago? 
see [here](https://github.com/akpw/mktxp/commit/985e976b827e8d70209702c5c323df18ae1989a5)

**Comment by shleeable** [comment]
@akpw I applogise for this. The docker stack was only updated two days ago... but I cloned the git a week and a half ago when the default was enabled.

This is just bad timing on my part.

https://github.com/akpw/mktxp-stack/commit/0e5c5ff336778409761279db1a2b606f73a9d760

**Comment by akpw** [comment]
OK I see, np
