### ISSUE TITLE
No correct IP address reporting

### ISSUE THREAD

**Issue by geno1961** [akpw/mktxp#138]
The tools detects an IPv4 address, which is not correct, based on the https://whatismyipaddress.com.

'mktxp' reports an IP address 62.73.72.255/ddns disabled, while my real external IP address is [46.10.214.65]/no-ip ddns

I am using 2 ISP and updating noip.com via script. Never being used mikrotik ddns cloud.

![Screenshot_20240506_183308](https://github.com/akpw/mktxp/assets/25261948/876bd701-ae3b-40c7-84a8-42efa7bd65a6)

![Screenshot_20240506_183209](https://github.com/akpw/mktxp/assets/25261948/77961452-2379-4282-ba5e-f8287658a0ea)

**Comment by rupadana** [comment]
i think the device routes Gateway is to IP 46.10.x

**Comment by geno1961** [comment]
Resolved,

This was the previous IP address given by my ISP when I used the MIKROTIK DDNS service.

**Comment by geno1961** [comment]
You can use the OPENDNS service to find your INTERNET visible IP address:
put [:resolve myip.opendns.com server=208.67.222.222]

The same service are provided by GOOGLE as well.
