### ISSUE TITLE
How to avoid getting data interactively?

### ISSUE THREAD

**Issue by qzq-123** [akpw/mktxp#139]
I'm having an issue where commands that would otherwise work fine are reporting errors when my router has too much data.

A screenshot of the error is below
![too-many-connections](https://github.com/akpw/mktxp/assets/51083159/0ed3dabf-51f0-40c5-a73c-46a10f6698f9)
![error-code](https://github.com/akpw/mktxp/assets/51083159/efbc36f5-d902-4458-8975-8edc3d814e1c)

A screenshot of the normal operation is as follows
![normal-code](https://github.com/akpw/mktxp/assets/51083159/d8c7fb78-b89f-4bdc-9488-4e3ee1313862)
It looks like it requires me to click if I want to see all the data, but how should this be implemented in the code?

Please let me know if I need to provide more information. Thanks
Python 3.8.10
RouterOS-7-api 0.18.1.dev0
routeros 7.12.1

**Comment by qzq-123** [comment]
` ssh mktxp_user@x.x.x.x "/ip/firewall/connection/print terse"`
I managed to get the data via ssh, but I think the api should be able to do the same, does anyone know what to do?

**Comment by Gero6700** [comment]
I have the same problem

**Comment by akpw** [comment]
is this filed at the right place? looks like an issue for routeros api, which is not exactly this project...
