### ISSUE TITLE
Error while running the mktxp

### ISSUE THREAD

**Issue by rupadana** [akpw/mktxp#140]
i've got this error while im adding my device, 

Exception occurred during processing of request from ('192.168.0.5', 37248)
mikrotik-mktxp  | Traceback (most recent call last):
mikrotik-mktxp  |   File "/usr/local/lib/python3.12/socketserver.py", line 318, in _handle_request_noblock
mikrotik-mktxp  |     self.process_request(request, client_address)
mikrotik-mktxp  |   File "/usr/local/lib/python3.12/socketserver.py", line 349, in process_request
mikrotik-mktxp  |     self.finish_request(request, client_address)
mikrotik-mktxp  |   File "/usr/local/lib/python3.12/socketserver.py", line 362, in finish_request
mikrotik-mktxp  |     self.RequestHandlerClass(request, client_address, self)
mikrotik-mktxp  |   File "/usr/local/lib/python3.12/socketserver.py", line 761, in __init__
mikrotik-mktxp  |     self.handle()
mikrotik-mktxp  |   File "/usr/local/lib/python3.12/http/server.py", line 436, in handle
mikrotik-mktxp  |     self.handle_one_request()
mikrotik-mktxp  |   File "/usr/local/lib/python3.12/http/server.py", line 424, in handle_one_request
mikrotik-mktxp  |     method()
mikrotik-mktxp  |   File "/usr/local/lib/python3.12/site-packages/prometheus_client/exposition.py", line 329, in do_GET
mikrotik-mktxp  |     self.wfile.write(output)
mikrotik-mktxp  |   File "/usr/local/lib/python3.12/socketserver.py", line 840, in write
mikrotik-mktxp  |     self._sock.sendall(b)
mikrotik-mktxp  | BrokenPipeError: [Errno 32] Broken pipe
mikrotik-mktxp  | ----------------------------------------
mikrotik-mktxp  | ----------------------------------------
mikrotik-mktxp  | Exception occurred during processing of request from ('192.168.0.5', 47338)
mikrotik-mktxp  | Traceback (most recent call last):
mikrotik-mktxp  |   File "/usr/local/lib/python3.12/socketserver.py", line 318, in _handle_request_noblock
mikrotik-mktxp  |     self.process_request(request, client_address)
mikrotik-mktxp  |   File "/usr/local/lib/python3.12/socketserver.py", line 349, in process_request
mikrotik-mktxp  |     self.finish_request(request, client_address)
mikrotik-mktxp  |   File "/usr/local/lib/python3.12/socketserver.py", line 362, in finish_request
mikrotik-mktxp  |     self.RequestHandlerClass(request, client_address, self)
mikrotik-mktxp  |   File "/usr/local/lib/python3.12/socketserver.py", line 761, in __init__
mikrotik-mktxp  |     self.handle()
mikrotik-mktxp  |   File "/usr/local/lib/python3.12/http/server.py", line 436, in handle
mikrotik-mktxp  |     self.handle_one_request()
mikrotik-mktxp  |   File "/usr/local/lib/python3.12/http/server.py", line 424, in handle_one_request
mikrotik-mktxp  |     method()
mikrotik-mktxp  |   File "/usr/local/lib/python3.12/site-packages/prometheus_client/exposition.py", line 329, in do_GET
mikrotik-mktxp  |     self.wfile.write(output)
mikrotik-mktxp  |   File "/usr/local/lib/python3.12/socketserver.py", line 840, in write
mikrotik-mktxp  |     self._sock.sendall(b)
mikrotik-mktxp  | BrokenPipeError: [Errno 32] Broken pipe

its only showed up when i added this device, if im not adding this device, the mktxp is working

**Comment by akpw** [comment]
> its only showed up when i added this device

so is this for a specific device, or for a specific number of monitored devices? 
assuming the latter, you can check e.g. [this one](https://github.com/akpw/mktxp/issues/29#issuecomment-1333434878)
