### ISSUE TITLE
Internet Bandwidth with VPN

### ISSUE THREAD

**Issue by raizdev** [akpw/mktxp#141]
I hosted my grafana and mktxp external, setting up vpn with wireguard with my mikrotik.
It seems that internet bandwidth is not going over my VPN.

Is it possible to add only one certain speedtest by server id? 

![image](https://github.com/akpw/mktxp/assets/31880091/dd4767e9-737d-46a1-afb8-dd3153737c55)

**Comment by Gero6700** [comment]
What are you really trying to monitor with that?
