### ISSUE TITLE
MKTXP1.2.6 version cannot obtain interface traffic in RouterOS5.25， mktxp_interface_rx_byte_total=0.0

### ISSUE THREAD

**Issue by xclsky1** [akpw/mktxp#142]
MKTXP1.2.6 version cannot obtain interface traffic in RouterOS5.25， mktxp_interface_rx_byte_total=0.0
![mktxp1](https://github.com/akpw/mktxp/assets/168082664/bd8cd271-c0b4-48cc-951a-d61a4521adb4)
![mktxp2](https://github.com/akpw/mktxp/assets/168082664/e8e8a26c-70d9-423d-a05d-0c2e365dcb07)

**Comment by akpw** [comment]
routeros versions below 6.x are not supported
