### ISSUE TITLE
Delete a device

### ISSUE THREAD

**Issue by Gero6700** [akpw/mktxp#143]
How can I delete a devide which was on the monitoring?

I have tried to comment in mktxp.conf but don't work and restart docker containers...

Can someone help?

**Comment by akpw** [comment]
no magic there, changing the mktxp.conf (comment out or remove the router entry) and restarting mktxp should work

**Comment by Gero6700** [comment]
I add a device in the configuration file and it is not added to the monitoring panel, but it is added to loki's panel. I have restarted the containers of mktxp, grafana and even prometheus.

I attach images.
![Screenshot_1](https://github.com/akpw/mktxp/assets/72683618/02f86077-1c0b-41a4-864a-3e598fdf4749)

![Screenshot_2](https://github.com/akpw/mktxp/assets/72683618/00b074be-d741-4902-84b7-9077f67ffcaa)
