### ISSUE TITLE
RouterOS-api upstream?

### ISSUE THREAD

**Issue by Strykar** [akpw/mktxp#144]
Hi, I am trying to package mktxp for Arch linux and have some Qs..

Looking at the listed deps at https://github.com/akpw/mktxp/blob/main/setup.py#L46 I assume `RouterOS-api` refers to https://github.com/socialwifi/RouterOS-api and not others like https://github.com/LaiArturs/RouterOS_API correct?

Also might be nice to mention that `python-poetry` is required as a build time dependency.

**Comment by akpw** [comment]
>RouterOS-api

correct, the mentioned dependency explicitly points to https://pypi.org/project/RouterOS-api/

> python-poetry is required as a build time dependency

not sure why, [the mktxp package](https://pypi.org/project/mktxp) is built using standard python setup tools

**Comment by Strykar** [comment]
@akpw Arch AUR package created - https://aur.archlinux.org/packages/python-mktxp

P.S. This collector and Dashboard rock! I will email Mikrotik support and suggest they add mktxp to the list at https://help.mikrotik.com/docs/display/ROS/API#API-APIexamples
