### ISSUE TITLE
Error getting system resource info from router.

### ISSUE THREAD

**Issue by imclint21** [akpw/mktxp#149]
Hi,

The exporter has a few problems and this disturbs the consistency of the metrics.

<img width="898" alt="image" src="https://github.com/akpw/mktxp/assets/5221349/0a388cd5-3f6f-46d8-9801-6f5853924d50">

Every 5 minutes the metrics return to zero:

<img width="917" alt="image" src="https://github.com/akpw/mktxp/assets/5221349/0ac1c75f-02be-48fd-a448-98e2d4881c6c">

**Comment by akpw** [comment]
this looks more like a connection problem, do you have a consistent link to that router? 
if you do, can you provide a bit more info about your mktxp env, ideally running it in verbose mode

**Comment by imclint21** [comment]
Sure,

I monitor 2 routers at the moment, 1 in the local network, 1 with the WAN IP.

Seems have new error now:
<img width="1199" alt="image" src="https://github.com/akpw/mktxp/assets/5221349/979f90b9-6086-4dda-95f4-115d613e4357">

**Comment by akpw** [comment]
and are the problems just for this specific server or also for the other one? since this does look like a connection link stability issue, so you might be randomly running into different problems while pulling various metrics, based on when the link breaks...

**Comment by imclint21** [comment]
Yep, but it would be great that mktxp handle this kind of problem, and still return the previous values!

**Comment by akpw** [comment]
> still return the previous values

well that'd be out of line with the general exporter architecture, leading to inconsistent metrics and other potential problems

mktxp does provide some system options for dealing with shaky network connections, you can experiment with those in the _mktxp.conf file, e.g. via ` mktxp edit -i -ed nano`.

**Comment by imclint21** [comment]
Okay I'll check it out!
