### ISSUE TITLE
Kubernetes Secrets Update

### ISSUE THREAD

**Issue by binaryronin** [akpw/mktxp#156]
The Kubernetes secret needs to be updated to match the newest configuration file. It currently uses the old style and was failing when I initially deployed it.

**Comment by akpw** [comment]
@clementnuss can you pls check / take care of this one? 
I would otherwise need to remove  kubernetes support from the project, no bandwidth on my end to maintain

**Comment by vertisan** [comment]
Hi, I like your project and I'm using it in my homelab :)
That's why some time ago I prepared a Helm chart for it: https://artifacthub.io/packages/helm/vrs-factory/prometheus-mikrotik-exporter
Ofc all credits are there ;) 
Feel free to use and/or contribute!

**Comment by binaryronin** [comment]
> @clementnuss can you pls check / take care of this one? I would otherwise need to remove kubernetes support from the project, no bandwidth on my end to maintain this sample deployment

I already had a branch with the changes on it but wasn't able to push/create a pr. It's a very simple change if you want me to do it, or send it to you in a Gist or something.

**Comment by akpw** [comment]
@binaryronin sure pls free to do a PR
