### ISSUE TITLE
Wireless client registration count incorrect

### ISSUE THREAD

**Issue by ventra007** [akpw/mktxp#160]
Hello,

The wlan / capsman collector only counts the amount of clients on wifi1 and wifi2 interfaces, not the additional interfaces generated by capsman.

`mktxp_wlan_registered_clients{channel="5785/ac/Ce", instance="mktxp:49090", job="mktxp", routerboard_address="***", routerboard_name="***"} | 10`

`mktxp_wlan_registered_clients{channel="2412/g", instance="mktxp:49090", job="mktxp", routerboard_address="***", routerboard_name="***"} | 6`

![2024-07-04 08_39_54-wifi-registered-clients](https://github.com/akpw/mktxp/assets/39557783/972aa13a-d289-4060-8f15-faad6451851c)

**Comment by akpw** [comment]
just to double check on what's going on there, can you run from cmd?
```
mktxp print -en router_name -cc
```

**Comment by ventra007** [comment]
Hi, thank you for replying. herewith the screenshot:

![2024-07-04 10_56_53-wifi-registered-clients](https://github.com/akpw/mktxp/assets/39557783/1c8ef5c0-6598-42d4-8dd6-1701338a1639)

**Comment by ventra007** [comment]
If I use the mktxp_capsman_registrations_count in the graph it kind of does what it needs to but the label is the raw data from Prometheus

**Comment by akpw** [comment]
Looks like the cmd numbers are correct? Then so should be the prometheus data, since there is no difference between how the counts are tracked / calculated.

**Comment by akpw** [comment]
still not sure I'm getting you, sounds like your expectation are around the wifi clients metrics to somehow correlate with the CAPsMAN clients ones? aren't they kind of different things, regardless of the packaging details of respective functionality?

the initial description of the issue does not seem to add up as well, maybe you can reformulate the perceived problem there?

**Comment by ventra007** [comment]
I guess the issue here is disjointed technologies from ROS. The latest wireless package and drivers only shows one menu, whereas before you used to get wireless and capsman separately.

under wireless, you have a historical graph of client connection but not capsman, and i'm just expecting to see a summary of all connected clients regardless of whether thy are on the wifi1, wifi2 or other capsman generated interfaces, since that is the amount of clients connected to that MikroTik i'm monitoring.

**Comment by akpw** [comment]
well the latest ROS packaging is a bit of a mess indeed, though the base underlying concepts there should not be changed as much. Just to avoid whatever ambiguities, can you do the relevant listings from your router terminal & then show they differ from their mktxp counterparts?
