### ISSUE TITLE
Errors on fresh prometheus verision (like 2.53) connected to metrics timestamps

### ISSUE THREAD

**Issue by 0xdeface** [akpw/mktxp#164]
Hello and thank for you product. Recently i have updated prometheus to 2.53 and have seen erros like:
msg="Error on ingesting samples with different value but same timestamp" 
after googling i found info [https://github.com/prometheus/prometheus/issues/14089#issuecomment-2107578174](url)
i checked /metrics | cut -d '}' | uniq -d and confirm that some metrics has dublicates.
in my case its: 
```
#
      2 mktxp_firewall_filter_total{log="0",name="| input | accept |  | icmp",routerboard_address="192.168.0.1",routerboard_name="KHV-IND-GW-0"}
      2 mktxp_firewall_mangle_total{log="0",name="| forward | mark-connection | LOW_PRIORITY",routerboard_address="192.168.0.1",routerboard_name="KHV-IND-GW-0"}
      2 mktxp_firewall_mangle_total{log="0",name="| forward | mark-packet | LOW_PRIORITY_IN",routerboard_address="192.168.0.1",routerboard_name="KHV-IND-GW-0"}
      2 mktxp_firewall_mangle_total{log="0",name="| postrouting | mark-packet | LOW_PRIORITY_OUT",routerboard_address="192.168.0.1",routerboard_name="KHV-IND-GW-0"}
      2 mktxp_firewall_nat_total{log="0",name="| dstnat | dst-nat |  | tcp",routerboard_address="192.168.0.1",routerboard_name="KHV-IND-GW-0"}
```

**Comment by akpw** [comment]
the firewall metric duplicities should have been fixed by #154, can you double with the latest build?
also, the `name` label seems to be different in all of the metrics you have mentioned above?

**Comment by tarumgod** [comment]
i have same problem with latest prometheus and mktxp...
`prometheus  | ts=2024-07-28T14:06:20.603Z caller=scrape.go:1744 level=warn component="scrape manager" scrape_pool=Mikrotik target=http://mikrotik:49090/metrics msg="Error on ingesting samples with different value but same timestamp" num_dropped=5`

**Comment by akpw** [comment]
@tarumgod OK, but can you track down those duplicate metrics?

**Comment by tarumgod** [comment]
@akpw sorry, its with IPSec peers. MKTXP Pooling a FEW routers...

> `mktxp_ipsec_peer_security_association{local_address="BB.BB.BB.BB",name="to-OFFICE",remote_address="AA.AA.AA.AA",routerboard_address="172.22.240.1",routerboard_name="Remote_POINT_1"} 0.0
> mktxp_ipsec_peer_responder{local_address="BB.BB.BB.BB",name="to-OFFICE",remote_address="AA.AA.AA.AA",routerboard_address="172.22.240.1",routerboard_name="Remote_POINT_1"} 1.0
> mktxp_ipsec_peer_natt_enabled{local_address="BB.BB.BB.BB",name="to-OFFICE",remote_address="AA.AA.AA.AA",routerboard_address="172.22.240.1",routerboard_name="Remote_POINT_1"} 0.0
> mktxp_ipsec_peer_security_association{local_address="CC.CC.CC.CC",name="to-OFFICE",remote_address="AA.AA.AA.AA",routerboard_address="172.22.220.1",routerboard_name="Remote_POINT_2"} 0.0
> mktxp_ipsec_peer_responder{local_address="CC.CC.CC.CC",name="to-OFFICE",remote_address="AA.AA.AA.AA",routerboard_address="172.22.220.1",routerboard_name="Remote_POINT_2"} 0.0
> mktxp_ipsec_peer_natt_enabled{local_address="CC.CC.CC.CC",name="to-OFFICE",remote_address="AA.AA.AA.AA",routerboard_address="172.22.220.1",routerboard_name="Remote_POINT_2"} 0.0`

**Comment by akpw** [comment]
OK thanks for tracking this down.

@phibos can you pls check? looks like more labels need to be added to this metric, to assure its uniqueness & prevent duplicities.

**Comment by phibos** [comment]
Thanks for reporting the issue. I have created a new PR #169 to fix this issue.

**Comment by fortellerq** [comment]
@akpw @phibos,
despite using version 1.2.7 I still get my prometheus log flooded by duplicates:
`msg="Error on ingesting samples with different value but same timestamp" num_dropped=2`

As I am reluctant to share firewall details publicly, I would rather keep amount of logs shared to minimum, but it is related to mktxp_firewall_nat_total being duplicated in metrics. I am happy to support any potential troubleshooting steps that might be required.

**Comment by phibos** [comment]
@fortellerq sorry for the late reply. I'm not the author of the firewall collector but I had a quick look. To identify the firewall metrics only the name label is used. The name label is a wired combination of different information like chain, the action and the comment. If available also the out_interface and the protocol are appended to the name label.

The name is generated by the following code.

https://github.com/akpw/mktxp/blob/4ee006a08b2b43b62c9258136aae73bf4fe5a203/mktxp/collector/firewall_collector.py#L84-L91

Let's assume you have at least two rules in the input chain with action=accept and you did not provide a comment. The name will look like ```| input | accept | ```. This will result in the same metric and one will be dropped by Prometheus as duplicated.

I have opened issue #214 to discuss some changes to the firewall collector. Feel free to join the discussion.
