### ISSUE TITLE
mktxp_interface_rx_drop_total not populating

### ISSUE THREAD

**Issue by JonathanThorpe** [akpw/mktxp#165]
Using mktxp  1.2.7, mktxp_interface_tx_drop_total appears to be empty - at least on the RB4011 running RouterOS 7.15.2 that I know has regular incrementing drops on an interface:

```
/interface/ethernet/print stats-detail 
 1 RS ;;; Connects to SW1 ether2
      name="ether2" driver-rx-byte=75 646 301 659 driver-rx-packet=108 943 132 driver-tx-byte=75 236 763 302 driver-tx-packet=109 003 558 rx-bytes=76 421 056 951 rx-unicast=105 192 582 rx-broadcast=4 608 255 rx-pause=0 rx-multicast=496 610 rx-fcs-error=0 rx-fragment=0 rx-unknown-op=0 rx-code-error=0 
      rx-jabber=0 rx-drop=1 353 956 tx-bytes=75 715 981 292 tx-unicast=109 156 228 tx-broadcast=9 554 tx-pause=0 tx-multicast=469 344 tx-collision=0 tx-excessive-collision=0 tx-multiple-collision=0 tx-single-collision=0 tx-deferred=0 tx-late-collision=0 tx-drop=0 tx-rx-64=4 924 532 tx-rx-65-127=26 704 182 
      tx-rx-128-255=7 942 108 tx-rx-256-511=117 165 032 tx-rx-512-1023=1 270 766 tx-rx-1024-1518=59 978 818 
```

Nothing shows up with `verbose_mode = True` and I also have `monitor = True` and `interface = True` as well. Have I missed something?

**Comment by akpw** [comment]
your listing shows `tx-drop=0`, so nothing seems wrong there for that specific label?

**Comment by JonathanThorpe** [comment]
Apologies, you're right - I meant to say "rx-drop" as per the title.

**Comment by JonathanThorpe** [comment]
Looking into this further, it appears to be related to how mktxp gets the interface stats:

Getting interface stats from the top-level `/interface` yields this (note no tx-drop or rx-drop):
```
[admin@PMTA-R1] > :put [/interface get 1]         
.id=*2;actual-mtu=1500;comment=Connects to SW1 ether2;default-name=ether2;disabled=false;fp-rx-byte=2643010439893;fp-rx-packet=3190324406;fp-tx-byte=1933235923942;fp-tx-packet=1590413290;l2mtu=1592;last-link-up-time=2024-07-09 21:55:38;link-downs=0;mac-address=C4:AD:34:DB:A1:FE;max-l2mtu=9578;mtu=1500;name=ether2;running=true;rx-byte=2655777425818;rx-packet=3190335071;slave=true;tx-byte=2706544389821;tx-packet=3314956793;tx-queue-drop=229;type=ether
```

However, going within the interface type (e.g. `/interface/ethernet`), I get

```
[admin@PMTA-R1] > :put [/interface ethernet get 1]
.id=*2;advertise=1G-baseT-full;arp=enabled;arp-timeout=auto;auto-negotiation=true;bandwidth=unlimited/unlimited;comment=Connects to SW1 ether2;default-name=ether2;disabled=false;driver-rx-byte=2718100255419;driver-rx-packet=3302144213;driver-tx-byte=2779069547705;driver-tx-packet=3426139610;l2mtu=1592;loop-protect=default;loop-protect-disable-time=00:05:00;loop-protect-send-interval=00:00:05;loop-protect-status=off;mac-address=C4:AD:34:DB:A1:FE;mtu=1500;name=ether2;orig-mac-address=C4:AD:34:DB:A1:FE;running=true;rx-broadcast=7419257;rx-bytes=2731316405902;rx-code-error=0;rx-drop=13392;rx-fcs-error=0;rx-flow-control=off;rx-fragment=0;rx-jabber=0;rx-multicast=12575554;rx-pause=0;rx-unicast=3282163956;rx-unknown-op=0;slave=true;switch=switch1;tx-broadcast=241089;tx-bytes=2793381050275;tx-collision=0;tx-deferred=0;tx-drop=0;tx-excessive-collision=0;tx-flow-control=off;tx-late-collision=0;tx-multicast=11913461;tx-multiple-collision=0;tx-pause=0;tx-rx-1024-1518=2617819093;tx-rx-128-255=137120102;tx-rx-256-511=2970583856;tx-rx-512-1023=37660493;tx-rx-64=263556726;tx-rx-65-127=664407207;tx-single-collision=0;tx-unicast=3424881896
```

I've been able to reproduce this on  6.49.13 (CRS125-24G-1S-2HnD) and 7.15.2 (RB4011iGS).

It might be that the behaviour of mktxp/datasource/interface_ds.py needs to change, such that it gets the stats from within the specific device type?

**Comment by akpw** [comment]
well, generally speaking the top level `/interface` probably makes more sense since the drops can happen on any interface. 

But then checking specifically for RB4011iGS+5HacQ2HnD-IN yes you're right, the drops for ethernet interfaces for this one indeed seems to be reported on that `/ethernet` level ¯\_(``)_/¯

so not sure about this one, maybe just test on both levels just in case

**Comment by akpw** [comment]
>needs to be tested & then merged on both levels

OK done, should be fixed by https://github.com/akpw/mktxp/commit/e76ace07ba72f1d491e2618bffffb333512ec18a
@JonathanThorpe, pls feel free to test for your use cases

**Comment by MarcWort** [comment]
Hi, @akpw im seems like you reverted the fix in https://github.com/akpw/mktxp/commit/f2810b56acfa4c5c2a4a34ae6b09b1802437fb57 ? 
Are there any long-term plans to make these metrics work?

**Comment by akpw** [comment]
>reverted the fix 

right, since it did not seem to be giving the right metrics. According to mikrotik wiki seem to be different things:
e.g.

>`/interface tx-drop (integer) Number of transmitted packets being dropped`

vs

> `/interface ethernet tx-drop (integer) Total count of transmitted frames that were dropped due to the already full output queue`

**Comment by MarcWort** [comment]
Thanks for the clarification on the reverted commit. Can we maybe introduce a new metric then? Maybe something like `mktxp_interface_frame_tx_drop_total`?

**Comment by akpw** [comment]
more like a dedicated collector for the `/interface/ethernet` metrics
