### ISSUE TITLE
Prometheus  device prefix

### ISSUE THREAD

**Issue by volga629-1** [akpw/mktxp#172]
This feature request for new config parameter for better filtering abilities in multi device environment 

Example

```
[mydevice]
device_prefix=mydevice-

```

**Comment by akpw** [comment]
just to clarify, what would that prefix do exactly?

**Comment by volga629-1** [comment]
It will added in front of all data sent to prometheus for specific device.

**Comment by akpw** [comment]
not sure what 'in front' means, assuming that would be about adding an additional device label? 
and if so, given there are already `routerboard_name` and `routerboard_address` labels, what would be the point?

**Comment by volga629-1** [comment]
For example site identification [site1]

**Comment by akpw** [comment]
the site prefix can be reflected in the `routerboard_name `, if need be? still looks a bit vague to me, so closing for now
