### ISSUE TITLE
Wrong name field in Netwatch collector

### ISSUE THREAD

**Issue by LinFor** [akpw/mktxp#175]
ROS v7.14 added name field for netwatch entries:

> *) winbox - added "Name" parameter under "Tools/Netwatch" menu;

But mktxp ignores this field, making its own "name" field from "host" field (or from "comment" if use_comments_over_names enabled).

**Comment by akpw** [comment]
mktxp currently uses consistent approach for this across all supported routerOS versions. 
To request support for a new field in v7.14+ versions, feel free to file a feature request.
