### ISSUE TITLE
Comment labels for interfaces

### ISSUE THREAD

**Issue by phyber** [akpw/mktxp#176]
Hi,

Thanks for writing `mktxp`, it's a great exporter. I was looking around for options regarding the interface comments, and found issue #54.

It would be nice if the comments for interfaces could be broken out of their names. I appreciate the backwards compatibility issues that you mention, so it could be an option. By default, keep the current behaviour, but if the appropriate option is enabled the comment could be moved to a `comment` label on the metric.

In fact, while writing the above I was looking into the metrics output and the code, and there are already some metrics which do this. Given this, it probably makes sense to make things consistent, and move all comments for every type of metric into a `comment` label, and make that the default at some point in the future.

I will probably spend some time looking into doing this myself (at least for interfaces, which is what I'm concerned with right now), but I don't have a time frame for a PR.

**Comment by phibos** [comment]
The SNMP exporter has an internal EnumAsInfo Type but for Prometheus it is simply a gauge.

```
# TYPE ifType_info gauge
ifType_info{ifAlias="",ifDescr="gre0",ifIndex="17",ifName="gre0",ifType="tunnel"} 1
```

Why not add something like
```
mktxp_interface_comment{name="ether1",routerboard_address="1.2.3.4",routerboard_name="example.org",comment="... the comment ..."} 1
```

This should be simple and does not break the backward compatibility. I can provide a PR but #206 should be merged before to prevent merge conflicts.

@akpw what do you think?

**Comment by akpw** [comment]
Yes separating interfaces names and comments in general make sense, just needs some attention to the existing `mktxp.conf` option + probably introducing another one to ensure full compatibility.

**Comment by forresthopkinsa** [comment]
I don't see how the linked PR solves this issue? The name fields in all the metrics still include the comment labels, which is IMO a huge miss. The dimension intended to be keyed for graphs should be low-cardinality and unchanging, and comments are not that.
