### ISSUE TITLE
HELP python_gc_objects_collected_total Objects collected during gc

### ISSUE THREAD

**Issue by asaddon** [akpw/mktxp#178]
Hello, I'm getting the following errors when I'm trying to use MKTXP on Docker ARM64 build.

`Prometheus Exporter for Mikrotik RouterOS, version 1.2.7`
`RouterOS version: 7.15.3`

On each refresh sometimes I get these lines.

`# HELP python_gc_objects_collected_total Objects collected during gc`
`# TYPE python_gc_objects_collected_total counter`
`python_gc_objects_collected_total{generation="0"} 517.0`
`python_gc_objects_collected_total{generation="1"} 6.0`
`python_gc_objects_collected_total{generation="2"} 0.0`
`# HELP python_gc_objects_uncollectable_total Uncollectable objects found during GC`
`# TYPE python_gc_objects_uncollectable_total counter`
`python_gc_objects_uncollectable_total{generation="0"} 0.0`
`python_gc_objects_uncollectable_total{generation="1"} 0.0`
`python_gc_objects_uncollectable_total{generation="2"} 0.0`
`# HELP python_gc_collections_total Number of times this generation was collected`
`# TYPE python_gc_collections_total counter`
`python_gc_collections_total{generation="0"} 55.0`
`python_gc_collections_total{generation="1"} 4.0`
`python_gc_collections_total{generation="2"} 0.0`
`# HELP python_info Python platform information`
`# TYPE python_info gauge`
`python_info{implementation="CPython",major="3",minor="12",patchlevel="5",version="3.12.5"} 1.0`
`# HELP process_virtual_memory_bytes Virtual memory size in bytes.`
`# TYPE process_virtual_memory_bytes gauge`
`process_virtual_memory_bytes 4.6297088e+07`
`# HELP process_resident_memory_bytes Resident memory size in bytes.`
`# TYPE process_resident_memory_bytes gauge`
`process_resident_memory_bytes 3.1072256e+07`
`# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.`
`# TYPE process_start_time_seconds gauge`
`process_start_time_seconds 1.72383879661e+09`
`# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.`
`# TYPE process_cpu_seconds_total counter`
`process_cpu_seconds_total 0.36`
`# HELP process_open_fds Number of open file descriptors.`
`# TYPE process_open_fds gauge`
`process_open_fds 25.0`
`# HELP process_max_fds Maximum number of open file descriptors.`
`# TYPE process_max_fds gauge`
`process_max_fds 1.048576e+06`
`# HELP mktxp_system_identity_info System identity`
`# TYPE mktxp_system_identity_info gauge`
`mktxp_system_identity_info{name="ICB",routerboard_address="175.107.*.*",routerboard_name="ICB"} 1.0`
`# HELP mktxp_system_uptime Time interval since boot-up`
`# TYPE mktxp_system_uptime gauge`
`mktxp_system_uptime{architecture_name="mmips",board_name="hEX",cpu="MIPS 1004Kc V2.15",routerboard_address="175.107.*.*",routerboard_name="ICB",version="7.15.3 (stable)"} 399813.0`
`# HELP mktxp_system_free_memory Unused amount of RAM`
`# TYPE mktxp_system_free_memory gauge`
`mktxp_system_free_memory{architecture_name="mmips",board_name="hEX",cpu="MIPS 1004Kc V2.15",routerboard_address="175.107.*.*",routerboard_name="ICB",version="7.15.3 (stable)"} 2.03976704e+08`
`# HELP mktxp_system_total_memory Amount of installed RAM`
`# TYPE mktxp_system_total_memory gauge`
`mktxp_system_total_memory{architecture_name="mmips",board_name="hEX",cpu="MIPS 1004Kc V2.15",routerboard_address="175.107.*.*",routerboard_name="ICB",version="7.15.3 (stable)"} 2.68435456e+08`
`# HELP mktxp_system_free_hdd_space Free space on hard drive or NAND`
`# TYPE mktxp_system_free_hdd_space gauge`
`mktxp_system_free_hdd_space{architecture_name="mmips",board_name="hEX",cpu="MIPS 1004Kc V2.15",routerboard_address="175.107.*.*",routerboard_name="ICB",version="7.15.3 (stable)"} 4.726784e+06`
`# HELP mktxp_system_total_hdd_space Size of the hard drive or NAND`
`# TYPE mktxp_system_total_hdd_space gauge`
`mktxp_system_total_hdd_space{architecture_name="mmips",board_name="hEX",cpu="MIPS 1004Kc V2.15",routerboard_address="175.107.*.*",routerboard_name="ICB",version="7.15.3 (stable)"} 1.6777216e+07`
`# HELP mktxp_system_cpu_load Percentage of used CPU resources`
`# TYPE mktxp_system_cpu_load gauge`
`mktxp_system_cpu_load{architecture_name="mmips",board_name="hEX",cpu="MIPS 1004Kc V2.15",routerboard_address="175.107.*.*",routerboard_name="ICB",version="7.15.3 (stable)"} 0.0`
`# HELP mktxp_system_cpu_count Number of CPUs present on the system`
`# TYPE mktxp_system_cpu_count gauge`
`mktxp_system_cpu_count{architecture_name="mmips",board_name="hEX",cpu="MIPS 1004Kc V2.15",routerboard_address="175.107.*.*",routerboard_name="ICB",version="7.15.3 (stable)"} 4.0`
`# HELP mktxp_system_cpu_frequency Current CPU frequency`
`# TYPE mktxp_system_cpu_frequency gauge`
`mktxp_system_cpu_frequency{architecture_name="mmips",board_name="hEX",cpu="MIPS 1004Kc V2.15",routerboard_address="175.107.*.*",routerboard_name="ICB",version="7.15.3 (stable)"} 880.0`
`# HELP mktxp_system_routerboard_voltage Supplied routerboard voltage`
`# TYPE mktxp_system_routerboard_voltage gauge`
`mktxp_system_routerboard_voltage{routerboard_address="175.107.*.*",routerboard_name="ICB"} 9.9`
`# HELP mktxp_system_routerboard_temperature Routerboard current temperature`
`# TYPE mktxp_system_routerboard_temperature gauge`
`mktxp_system_routerboard_temperature{routerboard_address="175.107.*.*",routerboard_name="ICB"} 44.0`
`# HELP mktxp_collection_time_total Total time spent collecting metrics in milliseconds`
`# TYPE mktxp_collection_time_total counter`
`mktxp_collection_time_total{name="IdentityCollector",routerboard_address="175.107.*.*",routerboard_name="ICB"} 731.8709050305188`
`mktxp_collection_time_total{name="SystemResourceCollector",routerboard_address="175.107.*.*",routerboard_name="ICB"} 546.5715510654263`
`mktxp_collection_time_total{name="HealthCollector",routerboard_address="175.107.*.*",routerboard_name="ICB"} 514.1619760543108`

and sometimes just this part:

`# HELP python_gc_objects_collected_total Objects collected during gc`
`# TYPE python_gc_objects_collected_total counter`
`python_gc_objects_collected_total{generation="0"} 517.0`
`python_gc_objects_collected_total{generation="1"} 16.0`
`python_gc_objects_collected_total{generation="2"} 0.0`
`# HELP python_gc_objects_uncollectable_total Uncollectable objects found during GC`
`# TYPE python_gc_objects_uncollectable_total counter`
`python_gc_objects_uncollectable_total{generation="0"} 0.0`
`python_gc_objects_uncollectable_total{generation="1"} 0.0`
`python_gc_objects_uncollectable_total{generation="2"} 0.0`
`# HELP python_gc_collections_total Number of times this generation was collected`
`# TYPE python_gc_collections_total counter`
`python_gc_collections_total{generation="0"} 56.0`
`python_gc_collections_total{generation="1"} 5.0`
`python_gc_collections_total{generation="2"} 0.0`
`# HELP python_info Python platform information`
`# TYPE python_info gauge`
`python_info{implementation="CPython",major="3",minor="12",patchlevel="5",version="3.12.5"} 1.0`
`# HELP process_virtual_memory_bytes Virtual memory size in bytes.`
`# TYPE process_virtual_memory_bytes gauge`
`process_virtual_memory_bytes 4.6313472e+07`
`# HELP process_resident_memory_bytes Resident memory size in bytes.`
`# TYPE process_resident_memory_bytes gauge`
`process_resident_memory_bytes 3.1072256e+07`
`# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.`
`# TYPE process_start_time_seconds gauge`
`process_start_time_seconds 1.72383879661e+09`
`# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.`
`# TYPE process_cpu_seconds_total counter`
`process_cpu_seconds_total 1.31`
`# HELP process_open_fds Number of open file descriptors.`
`# TYPE process_open_fds gauge`
`process_open_fds 25.0`
`# HELP process_max_fds Maximum number of open file descriptors.`
`# TYPE process_max_fds gauge`
`process_max_fds 1.048576e+06`

The config file I'm using, I disable everything to see if there is any unsupported setting but nothing worked.

`[ICB]`
`    enabled: True`
`    hostname: 175.107.x.x`
`    port: 8728`
`    username: admin`
`    password: **********`
`    use_ssl: False`
`    no_ssl_certificate: False`
`    ssl_certificate_verify: False`
`    plaintext_login: True`
`    dhcp: False`
`    installed_packages: False`
`    dhcp_lease: False`
`    interface: False`
`    monitor: False`
`    wireless: False`
`    wireless_clients: False`
`    connections: False`
`    connection_stats: False`
`    capsman: False`
`    capsman_clients: False`
`    poe: False`
`    netwatch: False`
`    use_comments_over_names: True`
`    public_ip: False`
`    route: False`
`    pool: False`
`    firewall: False`
`    neighbor: False`
`    ipv6_route: False`
`    ipv6_pool: False`
`    ipv6_firewall: False`
`    ipv6_neighbor: False`
`    user: False`
`    queue: False`
`    remote_dhcp_entry: None`
`    remote_capsman_entry: None`
`    check_for_updates: False`
`    bgp: False`
`    kid_control_assigned: False`
`    kid_control_dynamic: False`
`    lte: False`
`    ipsec: False`
`    switch_port: False`

**Comment by akpw** [comment]
assuming docker usage, what's the output of `$ docker logs mktxp`?

**Comment by asaddon** [comment]
> assuming docker usage, what's the output of `$ docker logs mktxp`?

Logs are empty but If I enter the container and run the mxtkp print commands, they're working fine.

**Comment by akpw** [comment]
given no logs and cmd line working, does not seem to be an mktxp issue
