### ISSUE TITLE
Connection to mikrotik Failed : 'bytes' object has no attribute 'encode'

### ISSUE THREAD

**Issue by Takane42** [akpw/mktxp#18]
i tried to connect to mikrotik using mktxp with correct credential etc. but i still cant connect it

Output when i tried tp run mktxp print

```bash
nata@--- : ~$ mktxp print -en Sample-Router -dc
Select metric option(s) to print out, or run 'mktxp print -h' to find out more
Connecting to router Sample-Router@172.16.1.2
2022-01-14 07:25:22 Connection to router Sample-Router@172.16.1.2 has failed: 'bytes' object has no attribute 'encode'
Error getting dhcp info from routerSample-Router@172.16.1.2: 'NoneType' object has no attribute 'get_resource'
No DHCP registration records
```

edit :
MKTXP version is 0.34
Python version is 3.8.10
Router that i use is hAP lite

**Comment by Takane42** [comment]
Nah im not. Im using SNMP Exporter instead of Mikrotik Exporter right now. Sorry

**Comment by akpw** [comment]
@Takane42 @JohanPhom, the error message above seems to indicate a connection problem. It can be networking, or most likely mismatched connection settings. Can you please post the relevant mktxp.conf router entry, along with the outcome of mkt 'ip service print' command?  Alternatively, you can check those and make sure the mktxp connection method matches corresponding api/api-ssl mkt services settings

**Comment by akpw** [comment]
closing for now, feel free to reopen with requested details
