### ISSUE TITLE
Loading Data failure

### ISSUE THREAD

**Issue by guitch94** [akpw/mktxp#184]
Hello Mr. Kuznetsov,

I managed to run your exporter in a Docker container, as explained in your documentation (by modifying the _mktxp.conf and mktxp.conf files). I am able to retrieve the information in Grafana. However, approximately every 5 seconds, the data stops being sent and then it resumes. I also tried running it locally with Docker Desktop and a Mikrotik router directly connected to my computer, but I still encounter the same issue. I attempted to modify the settings in _mktxp.conf, but that didn't resolve the problem either.

Have others reported this issue to you before? Do you have any ideas or suggestions on what I could explore further?

Thank you for your time and for your exporter.

Best regards,
Guillaume Blanco

**Comment by akpw** [comment]
have you checked on the logs? what's on the output of `$ docker logs mktxp`?
also try to run mktxp on the command line `mktxp print` etc., to see if there's any problem there?

**Comment by guitch94** [comment]
Hi, and thanks for your quick answer
Here are the logs :
<img width="878" alt="mktxp_logs" src="https://github.com/user-attachments/assets/4b7186fc-b59f-4daa-a212-156e7007216f">

Here is the print :
<img width="532" alt="mktxp_print" src="https://github.com/user-attachments/assets/92ba6890-e7ce-4642-9be2-66dc798d63dd">

Here is an export :
<img width="610" alt="mktxp_export" src="https://github.com/user-attachments/assets/d3c4d82e-0938-4b3c-a364-0f2db91d92e6">

The weird thing for me is that, I have acces to the data like here :
<img width="1261" alt="mktxp_data" src="https://github.com/user-attachments/assets/a7650d0d-9b7d-47e1-8228-6737926bbea6">

And then 5s later, I have this :  
<img width="1262" alt="mktxp_no_data" src="https://github.com/user-attachments/assets/c8eb93bb-61c8-497a-8b98-62c54beeb261">

**Comment by akpw** [comment]
OK so appears to be an issue with an unstable network connection. You can try adjusting settings like `socket_timeout` in the config, though essentially the problem seems to be related to your environment rather than a specific issue with mktxp itself.

**Comment by guitch94** [comment]
Ok, I'll try that, thank you !
