### ISSUE TITLE
Add matching semver tags to the container image

### ISSUE THREAD

**Issue by emerconn** [akpw/mktxp#185]
The container images do not have semver tags matching the Git semver tags.

Semver image tags are an intuitive way to help ensure that the intended deployment version ends up being the actual version deployed.

This is supported with the `tag-rules` parameter:

https://github.com/akpw/mktxp/blob/daa3e17eb4a3cee8482016976dc6a2ee3b3abcbe/.github/workflows/build-and-push.yaml#L53-L61

Like so:

```yaml
tag-rules: |
  type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
  type=raw,value=stable-{{date 'YYYYMMDDHHmmss'}},enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
  type=raw,value=gha-${{ github.run_id }}
  type=semver,pattern=v{{major}}.{{minor}}.{{patch}}
  type=semver,pattern=v{{major}}.{{minor}}
  type=semver,pattern=v{{major}}
```

**Comment by akpw** [comment]
@emerconnelly do you want to submit it as a PR?

**Comment by emerconnelly** [comment]
Sure! I will start working on it.

**Comment by MarcWort** [comment]
I just wanted to create the same issue :smile: 
@emerconnelly Any progress on the PR? Otherwise I would start doing it.

**Comment by akpw** [comment]
@MarcWort if you have time to do it, I'd say let's go with it

**Comment by MarcWort** [comment]
Sure see #187

**Comment by emerconn** [comment]
Sorry to reply late. I started testing my example but it didn't work: https://github.com/emerconn/mktxp/pkgs/container/mktxp

I figured it would since it's the same syntax I use it in my projects. This could be due to this workflow using a template, and the not the original Docker build and push action: https://github.com/docker/build-push-action

I plan to re-write the workflow without the template. This will allow for more future flexibility and safety in the case the template is ever deleted from GitHub.

**Comment by MarcWort** [comment]
Well, it works for me see: https://github.com/MarcWort/mktxp/pkgs/container/mktxp from this job https://github.com/MarcWort/mktxp/actions/runs/10726917561

**Comment by emerconn** [comment]
Oh, you got it working, nice! I must have done something wrong in my build.

I glanced at the build annotations and noticed the template is using deprecated commands & NodeJS versions. I still think it might be prudent to eventually move away from this template. I am happy to include this work as either part of this issue/PR, or a separate one.

**Comment by emerconn** [comment]
Also, I realized today from looking at other images, like the Python Alpine image which this build is based on, they do not include `v` in their tags. I probably should not have included the `v`'s like in `type=semver,pattern=v{{major}}.{{minor}}.{{patch}}` in my example.
