### ISSUE TITLE
Bruteforce Admin users api attack ?

### ISSUE THREAD

**Issue by ArcousSoftware** [akpw/mktxp#190]
![resim](https://github.com/user-attachments/assets/3c665f19-edb8-40c7-bc6e-ce29343aee95)

When I connect Grafana to Mikrotik, requests to the admin user start to continue. There is a malicious problem!!

**Comment by akpw** [comment]
Assuming it's not just a question for a wrong forum or smth along that lines, looks like there might be a malicious problem in your network environment. 

Regarding mktxp requirements, you might want to check [mikrotik device config](https://github.com/akpw/mktxp#mikrotik-device-config) section of the readme doc and set your device mktxp-user accordingly using the minimal required permissions. From there, you can then do `$ mktxp edit  -ed nano` (or just edit the mktxp.conf file directly) and make sure to setup the following section -- giving the above, using API-SSL seems to be a must in your case.
```
    username = username     # RouterOS user, needs to have 'read' and 'api' permissions
    password = password

    port = custom_IP_port      # RouterOS IP Port   
   
    use_ssl = false                         # enables connection via API-SSL servis
    no_ssl_certificate = False      # enables API_SSL connect without router SSL certificate
    ssl_certificate_verify = False  # turns SSL certificate
```

in case you have whatever other doubts, the mktxp connection is handled centrally from [here](https://github.com/akpw/mktxp/blob/main/mktxp/flow/router_connection.py) so feel free to review & suggest improvements
