### ISSUE TITLE
[Feature]  Configuration files per device

### ISSUE THREAD

**Issue by volga629-1** [akpw/mktxp#192]
Hello Everyone,
This is feature request to have export function  to have  more flexible configuration file management. 

Example site 50 devices.

Currently 

export function read config file with all devices based on [Device1] label.

New 

Use configuration files with drop in directory like 

```
/etc/mktxp/conf.d


root@mktxp01 ~> [/etc/mktxp]# ls -la conf.d/
total 12
drwxr-xr-x. 2 mktxp mktxp   62 Sep 21 23:53 .
drwxr-xr-x. 3 root  root    38 Sep 21 18:21 ..
-rw-r--r--. 1 mktxp mktxp 2993 Sep 21 23:38 device1.conf

``` 

New parameter 

# Assumption conf.d directory present  in cfg-dir path 
--cfg-name=

```
/usr/bin/mktxp export --cfg-dir /etc/mktxp --cfg-name=%i.conf

```

Systemd template 

/usr/lib/systemd/system/mktxp@.service

```

[Unit]
Description=MKTXP Exporter
After=network.target

[Service]
User=mktxp
Group=mktxp
RuntimeDirectory=mktxp
PIDFile=/run/mktxp/%i.pid
ExecStart=/usr/bin/mktxp export --cfg-dir /etc/mktxp --cfg-name=%i.conf

[Install]
WantedBy=default.target

```

**Comment by akpw** [comment]
@volga629-1 given `--cfg-dir` is already supported, wouldn't it be even more flexible to just use a specified config directory per device / group of devices?

**Comment by volga629-1** [comment]
Drop in conf.d is well know method in linux to organize extra configuration files.
This way is one extra directory and many configuration files with systemd template which seems very clean way to organize and allow to run on demand multiply device definitions. 



--cfg-dir is define default configuration path and  application by default save configuration files in defined path.

```
root@mktxp01 ~> [/etc/mktxp]# ls -lah
total 20K
drwxr-xr-x.   3 root  root    57 Sep 22 08:49 .
drwxr-xr-x. 110 root  root  8.0K Sep 21 23:38 ..
drwxr-xr-x.   2 mktxp mktxp   62 Sep 21 23:53 conf.d
-rw-r--r--.   1 mktxp mktxp 1.7K Sep 22 08:49 _mktxp.conf
-rw-r--r--.   1 mktxp mktxp 3.2K Sep 20 20:00 mktxp.conf
```

**Comment by akpw** [comment]
right, I'm talking about a different thing though. 
can you try `mktxp --cfg-dir your_per_ device_dir export` and see if that works for you

**Comment by volga629-1** [comment]
It generate default configurations on every run in conf.d  and it not loading drop in configuration file. 
I think it needs to have one default set of configuration files in --cfg-dir path and then preload from drop in based --cfg-name for specific configuration file to add. 

```

root@mktxp01 ~> [/etc/mktxp]# mktxp --cfg-dir /etc/mktxp/conf.d  export
Connecting to router Sample-Router@192.168.88.1
2024-09-22 11:56:20 Connection to router Sample-Router@192.168.88.1 has failed: timed out
Failed attemp to establish network connection to router: Sample-Router@192.168.88.1
2024-09-22 11:56:25 Running HTTP metrics server on: 0.0.0.0:49090
^CProcess ForkPoolWorker-4:
Process ForkPoolWorker-2:
Process ForkPoolWorker-3:
Process ForkPoolWorker-1:
root@mktxp01 ~> [/etc/mktxp]# ls -la conf.d/
total 12
drwxr-xr-x. 2 mktxp mktxp   62 Sep 21 23:53 .
drwxr-xr-x. 3 root  root    57 Sep 22 08:49 ..
-rw-r--r--. 1 mktxp mktxp 2993 Sep 21 23:38 device1.conf
-rw-r--r--. 1 mktxp mktxp 1686 Sep 21 23:41 _mktxp.conf
-rw-r--r--. 1 mktxp mktxp 3698 Sep 21 23:41 mktxp.conf
root@mktxp01 ~> [/etc/mktxp]#


```

**Comment by akpw** [comment]
mktxp checks the default config path for its config files, and copies the default ones in case it's not found there (typically on install). Now what I'm trying to tell you, you can already change that default config path using the `--cfg-dir` parameter:
```$ mktxp --cfg-dir your_custom_config_path export```

**Comment by volga629-1** [comment]
Please check structure for applications like sudo. 

- [ ] It allow flexible structure without have duplicate configuration. Also default cfg-path is not allow restart service for separate devices it relies on single mktpx.conf file . 
Drop in load configuration files based on any configuration files.
