### ISSUE TITLE
Is there a way to disable the bandwidth test?

### ISSUE THREAD

**Issue by infectiious** [akpw/mktxp#2]
Loving the project so far but wondering if there was a simple way to disable the bandwidth test?

Running in a docker container based on the compose file you posted in the other logged issue.

**Comment by akpw** [comment]
Can be added in the next version.

At that point, you can do the following:
> mktxp edit -i

that should open an mktxp internal config, where you can just set ```bandwidth_test_interval``` to a significantly higher value

**Comment by Brawn1** [comment]
Or you open your mktxp config folder and edit the _mktxp.conf file. ;-)

**Comment by infectiious** [comment]
Thanks all, yes editing the _mktxp.conf file was what I did in the end.

**Comment by akpw** [comment]
>Can be added in the next version

done, now can be disabled explicitly via setting  ```bandwidth = False``` in  the system config via running ```mktxp edit -i```

You can also edit ```_mktxp.conf``` directly of course, the above ```edit``` command is meant as a convenient way of opening the file in your system default editor.
