### ISSUE TITLE
General questions to MKTXP

### ISSUE THREAD

**Issue by dmnc-net** [akpw/mktxp#20]
Hi, I've just deployed MKTXP. At first, using Günter's (Brawn1') docker but next, I've switched over to stock Dockerfile ... @the-maldridge ... great work pal, only 61,3 MB footprint 👍. (Btw. [this](https://gist.github.com/dmnc-net/523c155bacc1b44fa4fac2d5fc7ab9b6) is my caveman-style deployment automation.)

I'm scraping wAP (LTE) on metered connection so I'd like to slow down. Is it possible to control the rate or MKTXP act just like a passthrough gateway and I have to set the rate within my Grafana Agent's `agent.yaml` (this is also my first time with Grafana and Prometheus).

And second, is it possible to set up multiple Mikrotik devices from a single `mktxp.conf`? Section header `[Sample-Router]` sounds like it is possible. ~~I've tried, got no error but also no data.~~ 
Edit: yes, it is possible

**Comment by akpw** [comment]
@dmnc-net yes it's possible to monitor multiple devices. regarding the scraping rates, the scrapes frequency is  controlled via prometheus config. in case you configure mktxp for parallel router fetching , you can additionally control max duration of overall & individual router scrapes
