### ISSUE TITLE
kubernetes manifests

### ISSUE THREAD

**Issue by nvtkaszpir** [akpw/mktxp#25]
Are you eager to accept PR with exemplary deployment on kubernetes?
If you don't feel like accepting it and thus maintaining it then no worries :)

Preview - https://github.com/nvtkaszpir/mktxp/tree/k8s/k8s

**Comment by nvtkaszpir** [comment]
CC @akpw

**Comment by akpw** [comment]
@nvtkaszpir thanks for the suggestion, at that point probably makes sense to keep this separate

**Comment by nvtkaszpir** [comment]
ok, no problem.
