### ISSUE TITLE
FR: Add Simple Queue metrics

### ISSUE THREAD

**Issue by tobi-nmx** [akpw/mktxp#27]
I would like to request addition of Simple Queue metrics. This would be a very valuable addition to track customer allocated vs. total available bandwith.

**Comment by akpw** [comment]
@tobi-nmx OK both simple / tree queues have been added. Updated the default dashboard as well, see below
Feel free to check it out in the latest / via [mktxp-stack](https://github.com/akpw/mktxp-stack), any feedback welcomed

<img width="818" alt="Queues" src="https://user-images.githubusercontent.com/5028474/210612942-e16f3da5-2022-4361-ae8d-85b1e3998ec4.png">

**Comment by tobi-nmx** [comment]
Works great. Thank you!!
