### ISSUE TITLE
Error with Python http server

### ISSUE THREAD

**Issue by ait0rn00b** [akpw/mktxp#29]
When adding a fourth Router to the config file (with mktxp edit using the default editor, nano) and restarting the service, I get the following error even though I have copied the config from another router that it's working.
When I delete the router entry, mktxp works fine again.
Thanks in advance

In case you want the config to examine:
`[CoreName]
    monitor = True
    pool = True
    no_ssl_certificate = False
    netwatch = True
    dhcp = True
    use_comments_over_names = False
    interface = True
    use_ssl = False
    firewall = True
    dhcp_lease = True
    ssl_certificate_verify = False
    capsman_clients = True
    poe = True
    wireless_clients = True
    capsman = True
    enabled = True
    wireless = True
    route = True
    hostname = IP
    username = whatever
    password = whatever
    port = 8728

[CoreName]
    monitor = True
    pool = True
    no_ssl_certificate = False
    netwatch = True
    dhcp = True
    use_comments_over_names = False
    interface = True
    use_ssl = False
    firewall = True
    dhcp_lease = True
    ssl_certificate_verify = False
    capsman_clients = True
    poe = True
    wireless_clients = True
    capsman = True
    enabled = True
    wireless = True
    route = True
    hostname = IP
    username = whatever
    password = whatever
    port = 8728

[CoreName]
    monitor = True
    pool = True
    no_ssl_certificate = False
    netwatch = True
    dhcp = True
    use_comments_over_names = False
    interface = True
    use_ssl = False
    firewall = True
    dhcp_lease = True
    ssl_certificate_verify = False
    capsman_clients = True
    poe = True
    wireless_clients = True
    capsman = True
    enabled = True
    wireless = True
    route = True
    hostname = IP
    username = whatever
    password = whatever
    port = 8728

[CoreName]
    monitor = True
    pool = True
    no_ssl_certificate = False
    netwatch = True
    dhcp = True
    use_comments_over_names = False
    interface = True
    use_ssl = False
    firewall = True
    dhcp_lease = True
    ssl_certificate_verify = False
    capsman_clients = True
    poe = True
    wireless_clients = True
    capsman = True
    enabled = True
    wireless = True
    route = True
    hostname = IP
    username = whatever
    password = whatever
    port = 8728`
![image](https://user-images.githubusercontent.com/74489662/167383658-ba77e4b9-8efc-48a6-afa8-f4ad30eae794.png)

**Comment by infiniti8** [comment]
Same problem:
![image](https://user-images.githubusercontent.com/80079858/203924370-1ea708f9-a367-42d1-bb61-06f8dbe16bae.png)

**Comment by infiniti8** [comment]
Its problem with Prometheus scrape_timeout. Just need to increase scrape_timeout in prometheus.yaml. 

This my config:

global:
  scrape_interval: 60s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  scrape_timeout: 60s # scrape_timeout is set to the global default (10s).

This solve my problem.

**Comment by akpw** [comment]
thanks @infiniti8. this does look like prometheus client dropping connections, and setting suitable `scrape_timeout` in the prometheus config should indeed fix it. 

an easy way to test prior to changing in production could be via [mktxp-stack](https://github.com/akpw/mktxp-stack), where the relevant settings are [as following](https://github.com/akpw/mktxp-stack/blob/main/prometheus/prometheus.yml)
