### ISSUE TITLE
Bandwidth totals

### ISSUE THREAD

**Issue by kaihendry** [akpw/mktxp#35]
Could the dashboard please have totals like:

![image](https://user-images.githubusercontent.com/765871/186914126-fc17df9a-61ee-43ae-a361-258d5729f73e.png)

I'm not sure how to make the prom query.

**Comment by akpw** [comment]
@kaihendry  you should be able to do it now via e.g. a simple queue for all bandwidth. 
this default dashboard panel should not be far from what you need? if so you can just tweak it to get the desired representation

<img width="1005" alt="Screenshot 2023-01-04 at 20 46 01" src="https://user-images.githubusercontent.com/5028474/210636941-5cc9c9b9-3eff-44ed-828a-1cc72106e801.png">
