### ISSUE TITLE
Internet bandwidth and latency with multiple routers

### ISSUE THREAD

**Issue by clorichel** [akpw/mktxp#36]
Thanks for your work on MKTXP ❤️ 

We've switched your provided Grafana dashboard variable:
- from "node" with query `label_values(mktxp_system_identity_info, routerboard_address)`
- to "name" with query `label_values(mktxp_system_identity_info, routerboard_name)`

Our problem is the `routerboard_address` is always the same in our usecase, so we cannot monitor many of those routers in this dashboard without this switch. We'd actually love to switch to "name" with `label_values(mktxp_system_identity_info, name)` (which is the MikroTik identity) instead of `routerboard_name` (which is the username) but some graphs don't have the `name` field.

One thing we mentioned, and that's the topic of this issue, is that the Internet Bandwidth (mktxp_internet_bandwidth) and the Internet Latency (mktxp_internet_latency) aren't filtered by the variable but used "as is", which basically makes them unusable when multiple routers are monitored.

With Grafana Explore we realised there is no way to actually filter those 🙃 

![Capture d’écran 2022-08-26 à 16 25 52](https://user-images.githubusercontent.com/12629433/186926870-511d6cdb-5cae-46fc-9896-276b6009afbb.png)
![Capture d’écran 2022-08-26 à 16 26 33](https://user-images.githubusercontent.com/12629433/186926893-be3ef1e3-c315-40fe-832f-0f716f736345.png)

Any chance you add the `routerboard_address` and/or `routerboard_name` to `mktxp_internet_bandwidth` and `mktxp_internet_latency` so they are usable when multiple routers are monitored?

**Comment by akpw** [comment]
@clorichel switching to `label_values(mktxp_system_identity_info, routerboard_name)`does make sense, so yes I can change it in the default dashboard.

regarding `mktxp_internet_bandwidth` and `mktxp_internet_latency`, currently the internet bandwidth test is run centrally from mktxp and not per individual devices. I can move the panels in the dashboard to the `MKTXP Metrics` section, to make it a bit more clear. 

Adding bandwidth per device could be a useful feature, it should be added it in the upcoming releases.
