### ISSUE TITLE
Netwatch

### ISSUE THREAD

**Issue by vsrod** [akpw/mktxp#4]
Please add the netwatch tool in the export options, i need it in my project and no prometheus exporter supports it.

Thank you for your attention.

**Comment by akpw** [comment]
@vsrod, thanks for the feature request. can be useful indeed, so will look to add in next release

**Comment by akpw** [comment]
@vsrod, this was added in [mktxp 0.30](https://pypi.org/project/mktxp/) + latest [grafana dashboard](https://grafana.com/grafana/dashboards/13679)
<img width="3074" alt="netwatch" src="https://user-images.githubusercontent.com/5028474/115145157-74108680-a050-11eb-98f7-f400061d7a12.png">
pls feel free to try out & comment / close

**Comment by vsrod** [comment]
Hello @akpw, when I use the password with symbols like (,.) i have the following error:

Connection to router prometheus@192.168.0.23 has failed: can't concat list to bytes

When I use the password without the symbols it works normally.

The netwatch monitoring is working from what i saw, i will do more tests during the week, anything i find you notice.


Thank you very much!

**Comment by akpw** [comment]
hi @vsrod 
>when I use the password with symbols like (,.) i have the following error

sure I can see how the `,` symbol in can be an issue -- thanks for reporting, will fix in next version

**Comment by akpw** [comment]
the pwd issue, fixed in the latest
