### ISSUE TITLE
mktxp print -dc crashes in presence of dhcp entries having 'all' as Server

### ISSUE THREAD

**Issue by mircoboschi** [akpw/mktxp#41]
Hello
I've found that _mxtxp_ cli crashes if there are DHCP static entries with Server='all' setting.
To reproduce:
1. Create a DHCP static Lease on Mikrotik device, setting Server to 'all' value.
2. Run _mktxp print -dc -en EntryName_

Cli will crash because that entries will not contains 'server' key.
To fix, simply add _if 'server' not in dhcp_lease_record: dhcp_lease_record['server']=""_
to cli/output/dhcp_out.py, after line 31 (for dhcp_lease_record in sorted...)

**Comment by akpw** [comment]
OK, reproduced & fixed in the latest -- thanks @mircoboschi
