### ISSUE TITLE
Metrics endpoint unresponsive after running for a day

### ISSUE THREAD

**Issue by 2m** [akpw/mktxp#45]
Yesterday I configured `mktxp` to export metrics from two Mikrotix devices: hEX router and cAP access point. After running for a day, today I noticed that `/metrics` endpoint was taking longer than 10 seconds to respond.

Here is my configuration:

```
[Router]
    enabled = True         # turns metrics collection for this RouterOS device on / off

    hostname = ...     # RouterOS IP address
    port = ...            # RouterOS IP Port

    username = ...     # RouterOS user, needs to have 'read' and 'api' permissions
    password = ...

    use_ssl = False                 # enables connection via API-SSL servis
    no_ssl_certificate = False      # enables API_SSL connect without router SSL certificate
    ssl_certificate_verify = False  # turns SSL certificate verification on / off

    dhcp = True                     # DHCP general metrics
    dhcp_lease = True               # DHCP lease metrics
    pool = True                     # Pool metrics
    interface = True                # Interfaces traffic metrics
    firewall = False                # Firewall rules matching traffic metrics
    monitor = True                  # Interface monitor metrics
    route = True                    # Routes metrics
    wireless = False                 # WLAN general metrics
    wireless_clients = False         # WLAN clients metrics
    capsman = False                  # CAPsMAN general metrics
    capsman_clients = False          # CAPsMAN clients metrics

    use_comments_over_names = False  # when available, forces using comments over the interfaces names

[WiFi-AP]
    enabled = True         # turns metrics collection for this RouterOS device on / off

    hostname = ...    # RouterOS IP address
    port = ...            # RouterOS IP Port

    username = ...    # RouterOS user, needs to have 'read' and 'api' permissions
    password = ...

    use_ssl = False                 # enables connection via API-SSL servis
    no_ssl_certificate = False      # enables API_SSL connect without router SSL certificate
    ssl_certificate_verify = False  # turns SSL certificate verification on / off

    dhcp = False                    # DHCP general metrics
    dhcp_lease = False              # DHCP lease metrics
    pool = False                    # Pool metrics
    interface = True                # Interfaces traffic metrics
    firewall = False                # Firewall rules matching traffic metrics
    monitor = True                  # Interface monitor metrics
    route = False                   # Routes metrics
    wireless = True                 # WLAN general metrics
    wireless_clients = True         # WLAN clients metrics
    capsman = False                 # CAPsMAN general metrics
    capsman_clients = False         # CAPsMAN clients metrics

    use_comments_over_names = False  # when available, forces using comments over the interfaces names
```

I am running `mktxp` on a Raspberry Pi 4 with 8 GB of ram.

Any parameters I could tune to keep the endpoint more responsive?

**Comment by 2m** [comment]
Hm, it might be something else. Not everytime `/metrics` endpoint becomes responsive again when I restart `mktxp`. That would point to an issue on the Mikrotik devices. But sometimes restarting `mktxp` helps. I need to dig into this more.

**Comment by 2m** [comment]
I disabled bandwidth collector that uses speedtest and now exporter endpoint seems more responsive. I'll monitor and let you know if this has solved the issue completely.

I edited `_mktxp.conf` file and added `bandwidth = False`.

**Comment by akpw** [comment]
Hello @2m, thanks for investigating. 

Do not think bandwidth collector should have much effect, since the processing there is currently done on mktxp host and not the routers. 

I can take a look at that over the weekend, in the meantime you can experiment with the following settings from ```_mktxp.conf```:
```
    initial_delay_on_failure = 120
    max_delay_on_failure = 900
    delay_inc_div = 5
```
which controls amount of delay on next connect. One way to troubleshoot would be setting ```verbose_mode = True```, and then running ```mktxp export``` from the command line to see what's going on there

**Comment by 2m** [comment]
Thanks, I will try these out.

Does the communication with mikrotik devices happen when `/metrics` endpoint is queried? It would seem so, as it takes a couple of seconds for `/metrics` to respond.

I think what happens, is due to misconfiguration on prometheus side, it sometimes DDoSes the endpoint with tens of scraping requests per second. :) And `/mktxp` endpoint does not respond in time when handling such a number of incoming requests.

**Comment by akpw** [comment]
Yes mktxp complies with the Prometheus pull-based architecture, so a misconfiguration of the scraping behaviour could indeed be a problem. 

One way to test would be using an alternative stack to monitor the MIkrotik devices, you can use a quick docker-based project such as [mktxp-stack](https://github.com/akpw/mktxp-stack) to check that out

**Comment by 2m** [comment]
Indeed, the problem was misconfiguration on the prometheus side. Thank you for the pointers!
