### ISSUE TITLE
mktxp_internet_bandwidth and mktxp_internet_latency are 0

### ISSUE THREAD

**Issue by takamaka-1337** [akpw/mktxp#5]
Thanks for very nice library first! I have problems with internet_bandwidth and internet_latency, which are 0. How can I debug that? From the beggining this feature has worked, but now few days it's just 0. Output from http://localhost:49090/ is below:

#HELP mktxp_internet_bandwidth Internet bandwidth in bits per second
#TYPE mktxp_internet_bandwidth gauge
mktxp_internet_bandwidth{direction="download"} 0.0
mktxp_internet_bandwidth{direction="upload"} 0.0
#HELP mktxp_internet_latency Internet latency in milliseconds
#TYPE mktxp_internet_latency gauge
mktxp_internet_latency 0.0

Please suggest what could be wrong

**Comment by akpw** [comment]
@takamaka-1337 thanks for pointing out. mktxp uses the speedtest library for bandwidth testing, and it looks like there was a bug there that was [already fixed](https://github.com/sivel/speedtest-cli/pull/769/commits/6e9a667b677b9dbc91a989ed1cdb343afbaf5273) in the latest. So to resolve, you can just upgrade that library on your mktxp system via:
```
 pip install speedtest-cli --upgrade
```

**Comment by takamaka-1337** [comment]
Thank you very much, this worked for sure! :)

**Comment by attilhacks** [comment]
Hi, I have 2 dockerized installations of the mktxp stack: both speed test is not showing data on the dashboard.

both work from CLI but not showing data on Grafana

# docker exec -it 39f1db989970 speedtest    
Retrieving speedtest.net configuration...
Testing from xxxxx...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by xxxxxx  [25.10 km]: 11.696 ms
Testing download speed................................................................................
Download: 116.26 Mbit/s
Testing upload speed......................................................................................................
Upload: 41.07 Mbit/s



docker exec -it d3d41dd83149 speedtest
Retrieving speedtest.net configuration...
Testing from xxxxxxx
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Dxxxxxxx  [1.49 km]: 49.902 ms
Testing download speed................................................................................
Download: 219.85 Mbit/s
Testing upload speed......................................................................................................
Upload: 17.60 Mbit/s



any idea?
thanks
