### ISSUE TITLE
capsman being fetched even though disabled

### ISSUE THREAD

**Issue by tuksi** [akpw/mktxp#50]
With `capsman = False` and `capsman_clients = False` mktxp docker will still fail while trying to access /caps-man API path.

```
/mktxp $ mktxp print -en Router -cc
Connecting to router Router@10.8.9.1
2022-11-15 13:44:36 Connection to router Router@10.8.9.1 has been established
Error getting caps-man registration table info from routerRouter@redacted: ('Error "no such command prefix" executing command b\'/caps-man/registration-table/print .tag=2\'', b'no such command prefix')
No CAPsMAN registration records
```

I am connecting to RouterOS v6.49.6 via API-SSL. Using docker image ghcr.io/akpw/mktxp:latest.

**Comment by tuksi** [comment]
This is mixed bug that got me totally confused. They are two issues:
1. Trying to contact CapsMan even though disabled
2. Error handling of CapsMan (Wireless package) disabled on RouterOS.

**Comment by akpw** [comment]
@tuksi both `capsman` and `capsman_clients` are used for controlling export to prometheus. 

While with `mktxp print ... -cc`, you're issuing a direct command explicitly requesting the info about  CAPsMAN clients. 
```
mktxp print -en MKT-GT -c -h
Displays selected metrics on the command line
...
Optional Arguments:
  -cc, --capsman_clients
                        CAPsMAN clients metrics
```

Not sure why this can be a problem - can you pls explain your use case of explicitly requesting CapsMan info on a device that is not configured for it?

**Comment by akpw** [comment]
closing, @tuksi pls feel free to reopen if further discussion / assistance is needed
