### ISSUE TITLE
Scrape times too long

### ISSUE THREAD

**Issue by HeGomGi** [akpw/mktxp#52]
Scrape durations are alway 5-6 second for each MikroTik device.
Each metric that I turn on or off adds 200-700ms of scrape time.
With more than 20 devices this is not really suitable.

Is there a possibility to run multiple instances of mktxp so routers can be processed in parallel? I sadly haven't found a way to point multiple instances to diffrent configs. 

I also tried verbose mode to see where these long times are coming from, but it brought me no insight

**Comment by akpw** [comment]
@HeGomGi 700ms per metric does sound long, what is your HW setup for running mktxp? 
Also, any chance you try with [mktxp/stack](https://github.com/akpw/mktxp-stack), to make sure this is not related to some configs issues?

To find out how the time is spent in individual collectors, the easiest is to look at the MKTXP Metrics in the supplied dashboard:

<img width="2325" alt="Screenshot 2022-12-07 at 12 34 49 PM" src="https://user-images.githubusercontent.com/5028474/206169541-a30f5806-c4a9-46db-add1-7b7dafae3f6f.png">

Parallel router scraping is a planned feature, should be added in the future releases

**Comment by HeGomGi** [comment]
I'm using an i7-10700 16GB connected to RB3011UiAS MikroTiks
I'll try using the stack

**Comment by akpw** [comment]
> i7-10700 16GB
interesting, that should be way high end for the purpose. likely a problem somewhere else, let me know about your findings. 

> using the stack
technically speaking, you should also be able to simulate parallel processing with multiple mktxp stacks running on the same machine. would require changing some ports in the configs (mktxp, prometheus scraping target, grafana) and that should be it.

**Comment by akpw** [comment]
@HeGomGi fyi, both parallel router fetch & configurable individual / overall scrape timeouts are now implemented
Feel free to check it out, configuring the default values
```
fetch_routers_in_parallel = False   # Set to True if you want to fetch multiple routers parallel
max_worker_threads = 5              # Max number of worker threads that can fetch routers. Meaningless if fetch_routers_in_parallel is set to False
    
max_scrape_duration = 10            # Max duration of individual routers' metrics collection 
total_max_scrape_duration = 30      # Max overall duration of all metrics collection 

```

 for your setup as needed, via: 
```
mktxp edit -ed nano -i
```
