### ISSUE TITLE
interface comment

### ISSUE THREAD

**Issue by EvilBart-PL** [akpw/mktxp#54]
Hi,

use_comments_over_names = False

But the comment is still there:

mktxp_interface_sfp_temperature{instance="127.0.0.1:49090", job="mktxp", name="ether7 (management switch 10G)"

If I change the comment on the router then in grafana things gets mixed I get new interface ...

is it possible to completly disable comment on name= ?
or split it to two vars: 
name= 
comment=

Regards

**Comment by EvilBart-PL** [comment]
Maybe this example will better explain what I mean:

changing comments works but it "generates" a new interface.
the "old" one stops collecting data and the "new" one starts ..
![image](https://user-images.githubusercontent.com/63264003/207310785-0b048511-8a6d-47a0-8479-e0900ce6cd75.png)

I just changed the comment ..

**Comment by EvilBart-PL** [comment]
I think I understand why You wrote "should catch up eventually" ..If You use the it daily or to control what is happening right now that ok.

However If you need for example 1 year of continuous data (whatever the comment on the interface is) that is becoming an issue to combine the data.

**Comment by akpw** [comment]
right, but then just changing the existing behaviour would also generate a backward compatibility problem. 
can be solved via a separate option in the future, unless considered an overkill
