### ISSUE TITLE
Change default location of config file?

### ISSUE THREAD

**Issue by colincurwen** [akpw/mktxp#56]
Hi there

Can I edit the setting for the default path for the config file for mktxp?

I set it up to run as a service (ubuntu 20.04), created a mktxp user for it to run under, moved the exec files from ~./local/bin to /usr/local/bin; everything seems to work great but I ran mktxp edit -i hoping to see the path for the config file in there so I could point to /mktxp (the folder I made to hold it) instead but no dice.

Is there somewhere else that info is located or do I need to add a line to tell it to look there instead?

Thanks,

Colin

**Comment by akpw** [comment]
@colincurwen the default config path is set to `~/mktxp`, currently it's not configurable. 
to run mktxp under a specific user, the easiest would be to have it installed under that user as well.

depending on your use-case, you can also run in docker or use [mktxp-stack](https://github.com/akpw/mktxp-stack) to have more flexibility on where to put the config files

**Comment by akpw** [comment]
@colincurwen OK I [added](https://github.com/akpw/mktxp/commit/208fc9e1ebb3fab4476398f9303dc24aabfd2cac) custom config files directory, you can try it out with the latest with the `--dir` option:
```
mktxp --dir <your_custom_mktxp_dir> show -cfg
MKTXP data config: <your_custom_mktxp_dir>/mktxp.conf
MKTXP internal config: <your_custom_mktxp_dir>/_mktxp.conf
```

all other commands like `export`, `print`, etc should work likewise as well

**Comment by colincurwen** [comment]
Hey that's great thanks so much I'll give it a try

> On Jan 4, 2023, at 9:16 AM, Arseniy Kuznetsov ***@***.***> wrote:
> 
> 
> @colincurwen OK I added custom config files directory, you can try it out with the latest with the --dir option:
> mktxp --dir <your_custom_mktxp_dir> show -cfg
> MKTXP data config: <your_custom_mktxp_dir>/mktxp.conf
> MKTXP internal config: <your_custom_mktxp_dir>/_mktxp.conf
> 
> all other commands like export, print, etc should work likewise as well
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>

--
Colin Curwen
(778) 991-2662 mobile
***@***.***
