### ISSUE TITLE
Tag a stable release

### ISSUE THREAD

**Issue by seberm** [akpw/mktxp#60]
Hello,
I really like your prometheus exporter! Do you plan to release/tag something like a stable version?

I would like to integrate the mktxp into my NixOS VM and maybe try to package this project directly into [nixpkgs](https://github.com/NixOS/nixpkgs). It would be great if you could create some kind of a release cycle so we could use tags directly instead of freezing on commit hashes.

Thanks!

**Comment by akpw** [comment]
@seberm thanks for the good words. Yes tagging stable releases makes sense of course, can do the initial one in a week or so (after some more testing / users' feedback on recently added features). Would that work?

**Comment by akpw** [comment]
@seberm fyi, tagged as discussed: [v1.1.0](https://github.com/akpw/mktxp/releases/tag/v1.1.0)
