### ISSUE TITLE
Ask mktxp for 2 or more router

### ISSUE THREAD

**Issue by muhalfzzz** [akpw/mktxp#64]
I want to ask how to edit 2 router or more on mktxp edit . if i want to add one router or more should i add a same config like below in under this configuration? or how? Thanks 

[router-1]
    enabled = True         # turns metrics collection for this RouterOS device on / off

    hostname = 10.10.10.10    # RouterOS IP address
    port = 8728             # RouterOS IP Port

    username = monitor     # RouterOS user, needs to have 'read' and 'api' permissions
    password = monitor

    use_ssl = False                 # enables connection via API-SSL servis
    no_ssl_certificate = False      # enables API_SSL connect without router SSL certificate
    ssl_certificate_verify = False  # turns SSL certificate verification on / off

    installed_packages = True       # Installed packages
    dhcp = True                     # DHCP general metrics
    dhcp_lease = True               # DHCP lease metrics
    connections = True              # IP connections metrics
    pool = True                     # Pool metrics
    interface = True                # Interfaces traffic metrics

    firewall = True                 # IPv4 Firewall rules traffic metrics
    ipv6_firewall = False           # IPv6 Firewall rules traffic metrics
    ipv6_neighbor = False           # Reachable IPv6 Neighbors

    poe = True                      # POE metrics
    monitor = True                  # Interface monitor metrics
    netwatch = True                 # Netwatch metrics
    public_ip = True                # Public IP metrics
    route = True                    # Routes metrics
    wireless = True                 # WLAN general metrics
    wireless_clients = True         # WLAN clients metrics
    capsman = False                  # CAPsMAN general metrics
    capsman_clients = False          # CAPsMAN clients metrics

    user = True                     # Active Users metrics
    queue = True                    # Queues metrics

    remote_dhcp_entry = None        # An MKTXP entry for remote DHCP info resolution in capsman/wireless

    use_comments_over_names = True  # when available, forces using comments over the interfaces names

**Comment by akpw** [comment]
yes you can have multiple router entries in the same config, just add them under. 
all entries should have different `[..]` names, and all are individually configurable

**Comment by muhalfzzz** [comment]
woaahh thank you so much for making this one. Its work perfect
