### ISSUE TITLE
Legend Names for integrations? 

### ISSUE THREAD

**Issue by rackifiaustin** [akpw/mktxp#65]
Hi there,

Is there any way for your to provide the "Legend" details for everything available?

I am learning a lot here and I want to use this to the fullest extent but I do not know where to find the Legend template names like:

{{public_address}}
{{version}} 
{{board_name}}

Thank you!

**Comment by akpw** [comment]
@rackifiaustin you can find available metric labels right in grafana metrics browser, for example:
<img width="1002" alt="Screenshot 2023-01-21 at 8 50 28" src="https://user-images.githubusercontent.com/5028474/213851079-0611d43e-e5ba-4563-b8b6-fe43bbf2ee25.png">

alternatively, you can inspect the raw mktxp endpoint output via checking http://<mktxp_host_ip>:49090, e.g.:
`curl  http://<mktxp_host_ip>:49090`

**Comment by rackifiaustin** [comment]
Hello,I am aware of that. It is under the “Verbose” option that I find there is a lot more options that I can’t find. The “template” names I am looking for. 
    	Get Outlook for iOS
    
  

 From: Arseniy Kuznetsov ***@***.***>Sent: Saturday, January 21, 2023 2:55 AMTo: akpw/mktxp ***@***.***>Cc: rackifiaustin ***@***.***>; Mention ***@***.***>Subject: Re: [akpw/mktxp] Legend Names for integrations? (Issue #65) 
Closed #65 as completed.
