### ISSUE TITLE
CPU Frequency shows zero

### ISSUE THREAD

**Issue by rackifiaustin** [akpw/mktxp#66]
The CPU frequency is showing "0" for some reason.

ARM64 - CCR2216 with RouterOS 7.7

Any idea why this might be?

**Comment by akpw** [comment]
showing where? mktxp does export cpu frequency as its `mktxp_system_cpu_frequency` metric, is this the one you're looking at?

also, not all mkt devices provide their cpu frequency, you can check on that via `system/resource/print`
