### ISSUE TITLE
Firewall blocks work

### ISSUE THREAD

**Issue by sasha2484** [akpw/mktxp#68]
Mikrotik system version - 7.6 (stable) Cloud Hosted Router
When running with default configs, I get this: (no metrics)

> (#) HELP python_gc_objects_collected_total Objects collected during gc
> (#) TYPE python_gc_objects_collected_total counter
> python_gc_objects_collected_total{generation="0"} 3596.0
> python_gc_objects_collected_total{generation="1"} 411.0
> python_gc_objects_collected_total{generation="2"} 0.0
> (#) HELP python_gc_objects_uncollectable_total Uncollectable object found during GC
> (#) TYPE python_gc_objects_uncollectable_total counter
> python_gc_objects_uncollectable_total{generation="0"} 0.0
> python_gc_objects_uncollectable_total{generation="1"} 0.0
> python_gc_objects_uncollectable_total{generation="2"} 0.0
> (#) HELP python_gc_collections_total Number of times this generation was collected
> (#) TYPE python_gc_collections_total counter
> python_gc_collections_total{generation="0"} 85.0
> python_gc_collections_total{generation="1"} 7.0
> python_gc_collections_total{generation="2"} 0.0
> (#) HELP python_info Python platform information
> (#) TYPE python_info gauge
> python_info{implementation="CPython",major="3",minor="11",patchlevel="1",version="3.11.1"} 1.0
> (#) HELP process_virtual_memory_bytes Virtual memory size in bytes.
> (#) TYPE process_virtual_memory_bytes gauge
> process_virtual_memory_bytes 4.20864e+07
> (#) HELP process_resident_memory_bytes Resident memory size in bytes.
> (#) TYPE process_resident_memory_bytes gauge
> process_resident_memory_bytes 3.4086912e+07
> (#) HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
> (#) TYPE process_start_time_seconds gauge
> process_start_time_seconds 1.67639501863e+09
> (#) HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
> (#) TYPE process_cpu_seconds_total counter
> process_cpu_seconds_total 0.43
> (#) HELP process_open_fds Number of open file descriptors.
> (#) TYPE process_open_fds gauge
> process_open_fds 21.0
> (#) HELP process_max_fds Maximum number of open file descriptors.
> (#) TYPE process_max_fds gauge
> process_max_fds 1.048576e+06

But if you put in the configuration:
firewall = False
poe = False
Then everything works fine
MKTXP v1.1.0 docker/pip

I assume that the problem is firewall_collector.py
Adding full rights to the user in mikrotik does not solve the problem.

Full logs:
> root@test:/home/user/(#) mktxp export
> Sample-Router@router: OK to connect
> Connecting to router Sample-Router@router
> 2023-02-14 17:25:51 Connection to router Sample-Router@ router has been established
> 2023-02-14 17:25:51 Running HTTP metrics server on port 49090
> ----------------------------------------
> Exception occurred during processing of request from ('IP', 59044)
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/socketserver.py", line 316, in _handle_request_noblock
>     self.process_request(request, client_address)
>   File "/usr/lib/python3.10/socketserver.py", line 347, in process_request
>     self.finish_request(request, client_address)
>   File "/usr/lib/python3.10/socketserver.py", line 360, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "/usr/lib/python3.10/socketserver.py", line 747, in __init__
>     self.handle()
>   File "/usr/lib/python3.10/http/server.py", line 432, in handle
>     self.handle_one_request()
>   File "/usr/lib/python3.10/http/server.py", line 420, in handle_one_request
>     method()
>   File "/usr/local/lib/python3.10/dist-packages/prometheus_client/exposition.py", line 270, in do_GET
>     status, headers, output = _bake_output(registry, accept_header, accept_encoding_header, params, False)
>   File "/usr/local/lib/python3.10/dist-packages/prometheus_client/exposition.py", line 105, in _bake_output
>     output = encoder(registry)
>   File "/usr/local/lib/python3.10/dist-packages/prometheus_client/exposition.py", line 198, in generate_latest
>     for metric in registry.collect():
>   File "/usr/local/lib/python3.10/dist-packages/prometheus_client/registry.py", line 97, in collect
>     yield from collector.collect()
>   File "/usr/local/lib/python3.10/dist-packages/mktxp/flow/collector_handler.py", line 125, in collect
>     yield from self.collect_sync()
>   File "/usr/local/lib/python3.10/dist-packages/mktxp/flow/collector_handler.py", line 44, in collect_sync
>     yield from collect_func(router_entry)
>   File "/usr/local/lib/python3.10/dist-packages/mktxp/collector/firewall_collector.py", line 33, in collect
>     metrics_records = [FirewallCollector.metric_record(router_entry, record) for record in firewall_filter_records]
>   File "/usr/local/lib/python3.10/dist-packages/mktxp/collector/firewall_collector.py", line 33, in <listcomp>
>     metrics_records = [FirewallCollector.metric_record(router_entry, record) for record in firewall_filter_records]
>   File "/usr/local/lib/python3.10/dist-packages/mktxp/collector/firewall_collector.py", line 60, in metric_record
>     name = f"| {firewall_record['chain']} | {firewall_record['action']} | {firewall_record['comment']}"
> KeyError: 'action'
> ----------------------------------------

**Comment by akpw** [comment]
@sasha2484 can you check now with the [latest](https://github.com/akpw/mktxp/pkgs/container/mktxp)?

**Comment by akpw** [comment]
closing, @sasha2484 let me know if you still have a problem

**Comment by sasha2484** [comment]
Docker-compose.yml:

version: '3.4'

networks:
  mktxp:

services:
  mktxp:
    container_name: mktxp
    image: ghcr.io/akpw/mktxp:latest
# stable-20230117072202
    user: root
    volumes:
      - './mktxp/:/root/mktxp/'
    ports:
    - protocol: tcp
      published: 49090
      target: 49090
#    networks:
#      mktxp:
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

**Comment by sasha2484** [comment]
mktxp.conf:
    enabled = True         # turns metrics collection for this RouterOS device on / off

    hostname = lo0.gw3.ROUTER
    port = 8728             # RouterOS IP Port
    username = prometheus
    password = PASS
    use_ssl = False                 # enables connection via API-SSL servis
    no_ssl_certificate = False      # enables API_SSL connect without router SSL certificate
    ssl_certificate_verify = False  # turns SSL certificate verification on / off

    installed_packages = True       # Installed packages
    dhcp = True                     # DHCP general metrics
    dhcp_lease = True               # DHCP lease metrics

    connections = True              # IP connections metrics
    connection_stats = True         # Open IP connections metrics

    pool = True                     # Pool metrics
    interface = True                # Interfaces traffic metrics

    firewall = True                 # IPv4 Firewall rules traffic metrics
    ipv6_firewall = True           # IPv6 Firewall rules traffic metrics
    ipv6_neighbor = True           # Reachable IPv6 Neighbors

    poe = True                      # POE metrics
    monitor = True                  # Interface monitor metrics
    netwatch = True                 # Netwatch metrics
    public_ip = True                # Public IP metrics
    route = True                    # Routes metrics
    wireless = True                 # WLAN general metrics
    wireless_clients = True         # WLAN clients metrics
    capsman = True                  # CAPsMAN general metrics
    capsman_clients = True          # CAPsMAN clients metrics

    user = True                     # Active Users metrics
    queue = True                    # Queues metrics

    remote_dhcp_entry = None        # An MKTXP entry for remote DHCP info resolution (capsman/wireless)

    use_comments_over_names = True  # when available, forces using comments over the interfaces names

**Comment by sasha2484** [comment]
If the latest version also specifies 
 
    firewall = False                 # IPv4 Firewall rules traffic metrics
    ipv6_firewall = False           # IPv6 Firewall rules traffic metrics
    ipv6_neighbor = False           # Reachable IPv6 Neighbors
    poe = False                      # POE metrics

Then everything works fine

**Comment by akpw** [comment]
>packages/mktxp/collector/firewall_collector.py", line 60, in metric_record
>name = f"| {firewall_record['chain']} | {firewall_record['action']} | 
>{firewall_record['comment']}"

looking at the logs, this does not seem to be the [code from the latest version](https://github.com/akpw/mktxp/blob/main/mktxp/collector/firewall_collector.py) 

Can you pls check if you are using the latest docker build?
```
docker pull ghcr.io/akpw/mktxp:gha-4177749398
```

**Comment by sasha2484** [comment]
Thank you so much, everything works!
