### ISSUE TITLE
dhcp collect error if set the lease item's to all

### ISSUE THREAD

**Issue by colinhd8** [akpw/mktxp#7]
if there's a dhcp lease item like this:
![image](https://user-images.githubusercontent.com/5259758/116672999-686c7a80-a9d5-11eb-923d-6f13a1c0cc96.png)
in routeros, then we will have the error:
![image](https://user-images.githubusercontent.com/5259758/116673127-92be3800-a9d5-11eb-95dc-bcbfcbc2aa0f.png)

routeros version: 6.47.8
mktxp version: latest

**Comment by akpw** [comment]
@colinhd8 OK thanks for the bug report, will fix in next version

**Comment by akpw** [comment]
@colinhd8: fixed, feel free to try out

**Comment by colinhd8** [comment]
Thank you for your quick fix, it's ok now.
