### ISSUE TITLE
config file get overwritten by the service

### ISSUE THREAD

**Issue by jktjkt** [akpw/mktxp#76]
When I start the daemon, the config file which sets up my routers gets overwritten, enforcing a particular order of statements. Since I'm managing all my config file centrally (via Ansible in my case), I'm seeing constant modifications because my centrally-manged config file has a structure which better fits my needs:

- I start with defining the target's connection details -- hostname, username, password, etc
- then I specify which collectors to use

I have not tried this, but I think this config overwriting will also mangle any comments, if used. Generally, I think it's better if a daemon doesn't write to its own config file.

**Comment by akpw** [comment]
@jktjkt this is related to fwd compatibility, mentioned e.g. [here](https://github.com/akpw/mktxp/issues/55#issuecomment-1346693843). the easiest way to work around is to make sure you have the latest version of the config files, with no need for the daemon to update it with new defaults

p.s.
mktxp is using (ConfigObj) [https://github.com/DiffSK/configobj] for config writing, which currently indeed does not pay much attention to the order & comments by default. ConfigObj does seem to have some related parameters, pls feel free to play with those & submit a PR if successful. I also do plan to figure it out at some point (when I get to it), replacing the ConfigObj with smth that can do the job if needed.
