### ISSUE TITLE
Please provide binary releases via Github

### ISSUE THREAD

**Issue by frittentheke** [akpw/mktxp#79]
Thanks for writing this exporter. It would be awesome if you could provide binary releases via Github like other exporters, e.g. the node exporter, do:  https://github.com/prometheus/node_exporter/releases/tag/v1.5.0

**Comment by hsmade** [comment]
But how would that work? As it's a Python package? There's no binary to distribute, and the docker image is already on the docker hub. What kind of binary are you looking for?

**Comment by frittentheke** [comment]
@hsmade true, and thanks for getting back to me.
It was a while back, but I likely opened this issue just blindly looking at the releases when looking for a successor 
for e.g. https://github.com/nshttpd/mikrotik-exporter without realizing your exporter was written in Python.

There are projects like https://github.com/indygreg/PyOxidizer which promise to produce an executable.
But if that really helps folks that could otherwise set up a virtual env or just use a container ... I don't know.
