### ISSUE TITLE
wrong cpu speed and no temperature for CRS312-4+8XG

### ISSUE THREAD

**Issue by evanrich** [akpw/mktxp#83]
Got this set up last night, super easy to do, however there are a few things missing:

Temperature for the unit, and cpu speed is wrong

it might just be your graph, but on one, it says 650Khz, the other it says 650Mhz (correct)
![image](https://github.com/akpw/mktxp/assets/518320/13aa11b1-00e4-4e0c-aabc-dab160f1a794)

for temperature, I looked through all the settings and couldn't find one to turn on.  This is what the dashboard shows:
![image](https://github.com/akpw/mktxp/assets/518320/2032c23e-6dd9-4139-818b-54525819da47)

however system health shows temperatures.  Is there another setting i can turn on to collect this?
![image](https://github.com/akpw/mktxp/assets/518320/866dbee2-7cba-47e7-9e3a-9ff969bec810)

I understand this is more for the routers, but CRS _IS_ a router (im not using SWOS).   This is on the latest 7.9.2

my config:
```
[Multigig-Switch]
    enabled = True         # turns metrics collection for this RouterOS device o                               n / off

    hostname = 192.168.xxx.yyy    # RouterOS IP address
    port = 8728             # RouterOS API / API-SSL service port

    username = user   # RouterOS user, needs to have 'read' and 'api' perm                               issions
    password = password

    use_ssl = False                 # enables connection via API-SSL servis
    no_ssl_certificate = False      # enables API_SSL connect without router SSL                                certificate
    ssl_certificate_verify = False  # turns SSL certificate verification on / of                               f

    installed_packages = True       # Installed packages
    dhcp = False                     # DHCP general metrics
    dhcp_lease = False               # DHCP lease metrics

    connections = True              # IP connections metrics
    connection_stats = False        # Open IP connections metrics

    pool = False                     # Pool metrics
    interface = True                # Interfaces traffic metrics

    firewall = True                 # IPv4 Firewall rules traffic metrics
    ipv6_firewall = False           # IPv6 Firewall rules traffic metrics
    ipv6_neighbor = False           # Reachable IPv6 Neighbors

    poe = False                     # POE metrics
    monitor = True                  # Interface monitor metrics
    netwatch = True                 # Netwatch metrics
    public_ip = True                # Public IP metrics
    route = True                    # Routes metrics
    wireless = False                 # WLAN general metrics
    wireless_clients = False         # WLAN clients metrics
    capsman = True                  # CAPsMAN general metrics
    capsman_clients = True          # CAPsMAN clients metrics

    user = True                     # Active Users metrics
    queue = True                    # Queues metrics

    remote_dhcp_entry = None        # An MKTXP entry for remote DHCP info resolu                               tion (capsman/wireless)

    use_comments_over_names = True  # when available, forces using comments over                                the interfaces names
```

**Comment by akpw** [comment]
hi @evanrich, thanks for the dashboard catch, will fix in next iteration. 

Regarding the switch temperature, the temperature fields tend to vary across various devices and mikrotik also likes to change it every now and then across ROS releases. For your example, this seems to be the case as of [ROS 7.5](https://forum.mikrotik.com/viewtopic.php?t=188851): 
>health - renamed "cpu-temperature" to "switch-temperature" on CRS312-...

I added a quick fix, feel free to test in [the latest](https://github.com/akpw/mktxp/pkgs/container/mktxp)

**Comment by akpw** [comment]
> thanks for the dashboard catch, will fix in next iteration.
done as well,-closing
