### ISSUE TITLE
PoE errors for routers without PoE support

### ISSUE THREAD

**Issue by sjmudd** [akpw/mktxp#85]
I have a number of different mikrotik routers and I notice a lot of logging errors such as this one:

```
Error getting PoE info from routerXXXX0@192.X.X.0: ('Error "no such command prefix" executing command b\'/interface/ethernet/poe/print .tag=819\'', b'no such command prefix')
Error getting PoE info from routerXXXX1@192.X.X.1: ('Error "no such command prefix" executing command b\'/interface/ethernet/poe/print .tag=485\'', b'no such command prefix')
Error getting PoE info from routerXXXX2@192.X.X.2: ('Error "no such command prefix" executing command b\'/interface/ethernet/poe/print .tag=423\'', b'no such command prefix')
Error getting PoE info from routerXXXX3@192.X.X.3: ('Error "no such command prefix" executing command b\'/interface/ethernet/poe/print .tag=418\'', b'no such command prefix')
```

Routers involved here are:
- RB5009UG+S+IN 
- CRS125-24G-1S-2HND-IN
- hAP ac²

There is no `/interface/ethernet/poe` menu option on these routers so all you do is generate unnecessary noise.
Therefore, I suspect that if this command generates an error you should not report it as an error as the device simply can not report what you want.

Routers are running ROS 7.10.1 so are all up to date as of writing this issue report.

Other than that thanks for writing this software. It's really helpful.

**Comment by sjmudd** [comment]
After only restarting the docker containers for a few minutes I see:
```
$ docker logs 5115ad7157d5 | grep -c "no such command prefix"
80
```
So this generates quite a few errors. I guess one per device per poll time.

**Comment by akpw** [comment]
Hi @sjmudd 
>There is no /interface/ethernet/poe menu option on these routers 

most of mkt devices do have this, which is the reason why the PoE option in [the base config file](https://github.com/akpw/mktxp#getting-started) defaults to ``True```. 

Setting it to ```False``` would prevent collecting PoE thus eliminating the noise.

**Comment by sjmudd** [comment]
Note: I have more models of Mikrotik than shown so for some of them the PoE options do actually work.

I still think that it would be better to either recognise from the model of the Mikrotik hardware if it will support this command and solicit anyone to update the list to fix any errors generated on other models not covered, but it may just be simpler to silently discard the error.  If silently discarding errors is not good just record the number of times it happens and with which commands. (??)

I'd certainly be happy to check the different models I have and help update the list if that would help. Others could do the same.

**Comment by akpw** [comment]
>more models of Mikrotik than shown so for some of them the PoE options do actually work.

the base config settings are per-router, so for routers with PoE supported just leave it enabled

>I still think that it would be better to either recognise from the model of the Mikrotik hardware 

a hard-coded list would probably be quite difficult to maintain?

>silently discard the error

that one is doable, though might be a bit misrepresentative for the case when PoE is supported but actually gives some errors

**Comment by sjmudd** [comment]
Then generate a counter per device and some comment somewhere indicating the reason for this.
Either way I just wanted to report this in case you were unaware.
