### ISSUE TITLE
Frequently get periods of no data returned on certain elements

### ISSUE THREAD

**Issue by belthesar** [akpw/mktxp#88]
Hey folks, looking to get a bit of help here. I have the mktxp exporter running via latest Docker container. In general, it works great! I get data from all the elements, I'm able to monitor traffic utilization, and everything is pretty nice. However, I do regularly notice that I receive periods of no data returned by the exporter, which causes a whole slough of data points in my Grafana graphs (using the companion Grafana dashboard published to Grafana) to return null. 

I'd like to smooth this out so that I do not have these weird periods of no data. Do I need to adjust my scraping config? Adjust a setting in Grafana? I'm less experienced with Prometheus currently, so I'm not exactly sure where to start troubleshooting here. Any insight on where to start looking and what I can adjust would be helpful. Thanks!

**Comment by belthesar** [comment]
I think I've resolved this. I took note of the global timing configs for the compose stack in https://github.com/akpw/mktxp-stack/blob/main/prometheus/prometheus.yml and configured this scraper to match those. While I don't have the same granularity of data (perhaps 5s was a _little_ aggressive?) I am certainly getting consistent returns every time now. It might be beneficial to provide recommended scrape intervals in the README, although perhaps folks just know not to scrape a device so hard? Unsure. Anywho, closing with comment for the benefit of others to discover.

**Comment by akpw** [comment]
@belthesar thanks for reporting on this one, scrape-related questions have indeed been discussed here a few times. 
As to recommended scrape parameters, obviously depends on specific needs & setups though as a quick reference, [the following](https://github.com/akpw/mktxp-stack/blob/main/prometheus/prometheus.yml) are the ones used in [mktxt-stack](https://github.com/akpw/mktxp-stack)
