### ISSUE TITLE
ipv6 support

### ISSUE THREAD

**Issue by baragoon** [akpw/mktxp#9]
Hi, any chances to run not only tcp (v4) ports but also tcp6 ports? Unable to add ipv6 addresses for Mikrotik routers.

**Comment by akpw** [comment]
Hello, yes I plan to add DHCPv6 & IPv6 firewall support at some point. Can prioritize those, if it helps

**Comment by baragoon** [comment]
I even can't connect mktxp to routers via ipv6, only ipv4 address can be used. And service is listeting ipv4:port nor ipv6:port

**Comment by jamerk** [comment]
I too would love ipv6 support, I'm using mktxp in the monitoring infrastructure for an ipv6 only environment

**Comment by akpw** [comment]
@jamerk @baragoon fyi the initial ipv6 support was added by [this PR](https://github.com/akpw/mktxp/pull/49) by @M0r13n, pls feel free to try out!
