### ISSUE TITLE
Duplicate HELP and metric for `mktxp_system_cpu_temperature`

### ISSUE THREAD

**Issue by philipcristiano** [akpw/mktxp#92]
With Telegraf scraping an mktxp (mktxp:stable-20230706091740) instance with a single device monitored I'm seeing Telegraf report:

```
reading text format failed: text format parsing error in line 73: second HELP line for metric name "mktxp_system_cpu_temperature"
```

Metrics are exposed as

```
# HELP mktxp_system_cpu_temperature CPU current temperature
# TYPE mktxp_system_cpu_temperature gauge
mktxp_system_cpu_temperature{routerboard_address="192.168.1.1",routerboard_name="Router"} 45.0
# HELP mktxp_system_cpu_temperature CPU current temperature
# TYPE mktxp_system_cpu_temperature gauge
mktxp_system_cpu_temperature{routerboard_address="192.168.1.1",routerboard_name="Router"} 39.0
```

With a CCR2004-1G-12S+2XS running ros 7.11

**Comment by philipcristiano** [comment]
[It appears](https://github.com/akpw/mktxp/blob/e54e4790cba13c9b01c35f88c1a66bff8a1838e7/mktxp/collector/health_collector.py#L37-L42) the `cpu_temperature` and `switch_temperature` are both mapped to `system_cpu_temperature`.

**Comment by akpw** [comment]
should be fixed by [this one](https://github.com/akpw/mktxp/commit/6cd62d233d2c3d4f306cde8324cb2f9e75a9d729)
