### ISSUE TITLE
internet availability check with ping only

### ISSUE THREAD

**Issue by Egyras** [akpw/mktxp#98]
as I dont like idea to launch periodic speed tests, would be possible to add just simple "pinger" and graph output to see internet availability ?

**Comment by akpw** [comment]
You can use Netwatch for this, which is already supported: 
<img width="1375" alt="image" src="https://github.com/akpw/mktxp/assets/5028474/f1e51687-57d3-4856-b79d-30beb6978499">

**Comment by Egyras** [comment]
> You can use Netwatch for this, which is already supported: <img alt="image" width="1375" src="https://user-images.githubusercontent.com/5028474/283447533-f1e51687-57d3-4856-b79d-30beb6978499.png">

ohhh, thought its only for internal IP's :)  Nice !!!

**Comment by Egyras** [comment]
@akpw thanks for hint.
